import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './v3.css';

const api = async (path, options = {}) => {
  const response = await fetch(`/api/v1${path}`, { credentials: 'include', headers: { 'content-type': 'application/json', ...(options.headers || {}) }, ...options });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data?.error?.message || `Request failed (${response.status})`);
  return data;
};
function Login({ onSuccess }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async event => { event.preventDefault(); setBusy(true); setError(''); try { await api('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); onSuccess(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <main className="login"><section><span className="eyebrow">FLESHLAB / V3 PREVIEW</span><h1>Operations<br/><i>in focus.</i></h1><p>Self-hosted V3 foundation. Use your existing FLESHLAB account.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <p className="error">{error}</p>}<button disabled={busy}>{busy ? 'Signing in…' : 'Enter V3'}</button></form></section><aside><p>FLESHLAB V3</p><strong>Built beside V2.<br/>Not over it.</strong></aside></main>;
}
const nav = ['Overview', 'Catalogue', 'Creators', 'Production', 'Growth', 'Commerce', 'System'];
function App() {
  const [user, setUser] = useState(null); const [catalogue, setCatalogue] = useState(null); const [dashboard, setDashboard] = useState(null); const [error, setError] = useState(''); const [section, setSection] = useState('Overview');
  const load = async () => { try { const current = await api('/auth/me'); setUser(current); if (!['admin', 'staff'].includes(current.role)) { setError('This V3 foundation is currently available to FLESHLAB staff and administrators.'); return; } const [c, d] = await Promise.all([api('/admin/catalogue'), api('/dashboard/admin')]); setCatalogue(c); setDashboard(d); } catch (e) { if (!/Authentication is required|Session is invalid/.test(e.message)) setError(e.message); } };
  useEffect(() => { load(); }, []);
  if (!user) return <Login onSuccess={load} />;
  if (error) return <main className="denied"><span className="eyebrow">FLESHLAB V3</span><h1>Access limited.</h1><p>{error}</p></main>;
  const metrics = dashboard?.metrics || {}; const counts = catalogue?.counts || {};
  return <div className="app"><aside className="rail"><a className="brand" href="/v3/">FLESH<span>LAB</span><small>V3 PREVIEW</small></a><nav>{nav.map(item => <button key={item} className={section === item ? 'active' : ''} onClick={() => setSection(item)}>{item}</button>)}</nav><div className="rail-foot"><span>{user.email}</span><button onClick={async () => { await api('/auth/logout', { method: 'POST', body: '{}' }); setUser(null); setCatalogue(null); }}>Sign out</button></div></aside><main className="workspace"><header><div><span className="eyebrow">V3 / {section.toUpperCase()}</span><h1>{section === 'Overview' ? 'Good evening.' : section}</h1></div><div className="live"><i></i> Self-hosted / live data</div></header>{section === 'Overview' ? <><section className="hero"><div><span>Operations snapshot</span><h2>What needs your<br/><i>attention?</i></h2><p>Only database-backed signals are shown in V3.</p></div><dl><div><dt>Recruitment queue</dt><dd>{metrics.applications_pending ?? '—'}</dd><small>applications awaiting review</small></div><div><dt>Published library</dt><dd>{counts.videos ?? '—'}</dd><small>live catalogue videos</small></div></dl></section><section className="metric-grid"><Metric label="Brands" value={counts.brands}/><Metric label="Performers" value={counts.performers}/><Metric label="Video credits" value={counts.credits}/><Metric label="Active accounts" value={metrics.active_accounts}/></section><section className="split"><article><span className="eyebrow">CATALOGUE HEALTH</span><h3>Real catalogue, ready for V3.</h3><p>{counts.brands} brands, {counts.performers} performers, {counts.videos} videos and {counts.credits} valid performer relationships are available from PostgreSQL.</p><button onClick={() => setSection('Catalogue')}>Open catalogue</button></article><article><span className="eyebrow">SYSTEM</span><h3>Foundation status</h3><p>Authentication, role enforcement, catalogue projection and deployment health are connected. Commerce and AI execution are deliberately not activated.</p></article></section></> : <Catalogue section={section} catalogue={catalogue}/> }</main></div>;
}
function Metric({ label, value }) { return <article className="metric"><span>{label}</span><strong>{value ?? '—'}</strong><small>PostgreSQL</small></article>; }
function Catalogue({ section, catalogue }) { if (section !== 'Catalogue') return <section className="coming"><span className="eyebrow">V3 DOMAIN</span><h2>{section}</h2><p>This V3 domain is intentionally not represented by a V2 page clone. Its vertical slice follows after the foundation and catalogue acceptance.</p></section>; return <section className="catalogue"><div className="catalogue-head"><div><span className="eyebrow">CATALOGUE</span><h2>Live library.</h2></div><p>{catalogue.videos.length} published records</p></div><div className="video-grid">{catalogue.videos.slice(0, 12).map(video => <article key={video.id}>{video.primary_thumbnail_url ? <img src={video.primary_thumbnail_url} alt="" loading="lazy"/> : <div className="poster"/>}<div><span>{video.performer_names?.join(' · ') || 'Unassigned'}</span><h3>{video.title}</h3><small>{video.access_tier || 'catalogue'} · {video.status}</small></div></article>)}</div></section>; }
createRoot(document.getElementById('root')).render(<App/>);
