import React, { useEffect, useState } from 'react';
import './public.css';

const get = async path => { const response = await fetch(`/api/v3/public${path}`, { headers: { accept: 'application/json' } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data?.error?.message || 'This page is unavailable.'); return data; };
const esc = value => String(value || '').replace(/[<>]/g, '');
const publicImage = value => /^https?:\/\//i.test(String(value || '')) ? value : undefined;
const imageFor = (record = {}) => publicImage(record.thumbnail_url || record.poster_url || record.trailer_url || record.legacy_cover_image_url || record.legacy_profile_image_url || record.legacy_logo_url || record.cover_asset_reference);
const labelFor = (record = {}) => record.title || record.display_name || record.name || 'FLESHLAB';
const runtime = value => value == null ? '' : `${Math.floor(Number(value) / 60)}:${String(Number(value) % 60).padStart(2, '0')}`;
const releaseDate = value => value ? new Date(value).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' }) : '';

function Seo({ title, description, image }) {
  useEffect(() => {
    const canonical = `${window.location.origin}${window.location.pathname}`; document.title = title;
    [['name', 'description', description], ['property', 'og:title', title], ['property', 'og:description', description], ['property', 'og:image', publicImage(image)]].forEach(([attribute, name, content]) => { if (!content) return; let element = document.head.querySelector(`meta[${attribute}="${name}"]`); if (!element) { element = document.createElement('meta'); element.setAttribute(attribute, name); document.head.appendChild(element); } element.setAttribute('content', String(content).slice(0, 300)); });
    let link = document.head.querySelector('link[rel="canonical"]'); if (!link) { link = document.createElement('link'); link.rel = 'canonical'; document.head.appendChild(link); } link.href = canonical;
    let schema = document.head.querySelector('#fleshlab-public-schema'); if (!schema) { schema = document.createElement('script'); schema.id = 'fleshlab-public-schema'; schema.type = 'application/ld+json'; document.head.appendChild(schema); } schema.textContent = JSON.stringify({ '@context': 'https://schema.org', '@type': 'WebSite', name: 'FLESHLAB', url: canonical, description: String(description || '').slice(0, 300), ...(publicImage(image) ? { image: publicImage(image) } : {}) });
  }, [title, description, image]); return null;
}

function Shell({ children, seo = {} }) {
  const links = <><a href="/v3/home">Home</a><a href="/v3/videos">Videos</a><a href="/v3/performers">Performers</a><a href="/v3/collections">Collections</a><a href="/v3/brands">Brands</a><a className="nav-join" href="https://earn.fleshlab.online">Earn with FLESHLAB <span aria-hidden="true">↗</span></a></>;
  return <div className="public-shell"><Seo title={seo.title || 'FLESHLAB | Independent creator studio'} description={seo.description || 'Creator-led films from FLESHLAB.'} image={seo.image}/><header className="public-nav"><a href="/v3/home" className="public-brand" aria-label="FLESHLAB home"><b>FLESH</b><span>LAB</span><small>STUDIO / V3</small></a><nav aria-label="Public navigation">{links}</nav><details className="public-mobile-nav"><summary aria-label="Open public navigation"><span>Menu</span><i aria-hidden="true">+</i></summary><div aria-label="Mobile public navigation">{links}</div></details></header>{children}<footer className="public-footer"><div className="footer-brand"><a className="public-brand" href="/v3/home"><b>FLESH</b><span>LAB</span></a><p>Independent, creator-led production.<br/>Stories made with presence.</p></div><div><span className="footer-label">Explore</span><div className="footer-links"><a href="/v3/home">Home</a><a href="/v3/videos">Videos</a><a href="/v3/performers">Performers</a><a href="/v3/collections">Collections</a><a href="/v3/brands">Brands</a></div></div><div><span className="footer-label">Connect</span><div className="footer-links"><a href="https://earn.fleshlab.online">Earn with FLESHLAB ↗</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/compliance">Legal & compliance</a><a href="mailto:studiosupport@fleshlab.online">Contact support</a></div></div><small className="footer-copyright">© {new Date().getFullYear()} FLESHLAB. Published catalogue only.</small></footer></div>;
}

function Image({ record, alt, eager = false, className = '' }) { const src = imageFor(record); return <div className={`public-image ${className}`}>{src ? <img src={src} alt={alt} loading={eager ? 'eager' : 'lazy'} {...(eager ? { fetchPriority: 'high' } : {})}/> : <span className="image-fallback">FLESHLAB</span>}</div>; }
function videoHref(video) { return `/v3/videos/${encodeURIComponent(video.slug)}`; }
function CardMeta({ video }) { const people = video.performers?.map(item => item.name).filter(Boolean).join(' · '); const facts = [people || video.brand_name || 'FLESHLAB original', runtime(video.duration_seconds || video.runtime_seconds), releaseDate(video.release_date || video.published_at)].filter(Boolean); return <div className="public-card-meta"><b>{esc(video.title)}</b><small>{facts.join('  ·  ')}</small></div>; }
function ReleaseCard({ video, lead = false, position }) { return <a className={`release-card ${lead ? 'lead' : ''}`} href={videoHref(video)}><Image record={video} alt={labelFor(video)} eager={lead}/><div className="release-overlay"><span className="release-index">{position ? String(position).padStart(2, '0') : '01'}</span><span className="release-type">{lead ? 'FEATURED RELEASE' : 'PUBLISHED FILM'}</span><CardMeta video={video}/><span className="release-arrow" aria-hidden="true">↗</span></div></a>; }
function PerformerCard({ performer, index }) { return <a className="performer-card" href={`/v3/performers/${encodeURIComponent(performer.slug)}`}><Image record={performer} alt={`Portrait of ${performer.display_name}`}/><div className="performer-overlay"><span className="performer-index">{String(index + 1).padStart(2, '0')}</span><div><span className="eyebrow">PERFORMER</span><h3>{esc(performer.display_name)}</h3><p>{esc(performer.bio || performer.nationality || 'Discover the work.')}</p><small>{performer.video_count != null ? `${performer.video_count} published video${performer.video_count === 1 ? '' : 's'}` : 'View profile'} <span aria-hidden="true">↗</span></small></div></div></a>; }
function CollectionCard({ collection, feature = false }) { return <a className={`collection-card ${feature ? 'feature' : ''}`} href={`/v3/collections/${encodeURIComponent(collection.slug)}`}><Image record={{ cover_asset_reference: collection.cover_asset_reference, legacy_cover_image_url: collection.legacy_cover_image_url }} alt={collection.title}/><div className="collection-copy"><span className="eyebrow">COLLECTION / {collection.video_count || 0} FILMS</span><h3>{esc(collection.title)}</h3><p>{esc(collection.description || 'A considered FLESHLAB selection.')}</p><span className="text-link">Enter collection <b aria-hidden="true">↗</b></span></div></a>; }
function SectionHead({ eyebrow, title, href, action = 'View all' }) { return <div className="public-section-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{href && <a href={href}>{action} <span aria-hidden="true">↗</span></a>}</div>; }

function BrandHome() {
  const [data, setData] = useState(null); const [error, setError] = useState(''); useEffect(() => { get('/homepage').then(setData).catch(e => setError(e.message)); }, []);
  const hero = data?.hero; const heroRecord = hero?.record || {}; const seo = { title: hero?.title ? `${hero.title} | FLESHLAB` : 'FLESHLAB | Real people. Real stories.', description: hero?.summary || 'Premium creator-led films, real chemistry and stories made with presence.', image: hero?.image };
  const featured = data?.featured_videos || []; const newReleases = data?.new_releases || []; const performers = data?.featured_performers || []; const collections = data?.featured_collections || [];
  return <Shell seo={seo}><main className="public-home">{error ? <div className="public-main public-state"><p className="error">{error}</p></div> : !data ? <div className="public-main public-state"><div className="public-empty">Loading the studio…</div></div> : <>
    <section className="home-hero"><div className="hero-backdrop">{hero?.image && <img className="hero-media" src={publicImage(hero.image)} alt="" fetchPriority="high"/>}<div className="hero-light"/><div className="hero-grain"/></div><div className="hero-content public-main"><div className="hero-copy"><span className="eyebrow">{hero?.eyebrow || 'FLESHLAB ORIGINAL'}</span><h1>{esc(hero?.title || 'Real people. Real stories.')}</h1><p>{esc(hero?.summary || 'Creator-led films, authentic chemistry and a world of performers made to be watched with intention.')}</p><div className="public-actions"><a className="public-primary" href={hero?.cta_target || '/v3/videos'}>{hero?.cta_label || 'Watch now'} <span aria-hidden="true">↗</span></a><a className="public-secondary" href="/v3/performers">Meet the performers</a></div></div><div className="hero-feature-card"><span className="eyebrow">NOW IN FOCUS</span><strong>{esc(labelFor(heroRecord))}</strong><div><span>{hero?.kind === 'performer' ? 'Performer profile' : hero?.kind === 'collection' ? 'Curated collection' : 'Published release'}</span><a href={hero?.kind === 'performer' ? `/v3/performers/${heroRecord.slug}` : hero?.kind === 'collection' ? `/v3/collections/${heroRecord.slug}` : heroRecord.slug ? videoHref(heroRecord) : '/v3/videos'} aria-label={`Open ${labelFor(heroRecord)}`}>Open story <b aria-hidden="true">↗</b></a></div></div></div><div className="hero-scroll" aria-hidden="true"><span>Scroll to explore</span><i/></div></section>
    <div className="brand-ticker" aria-label="FLESHLAB studio statement"><span>FLESHLAB</span><i>Real people</i><span>Independent production</span><i>Stories with presence</i><span>Creator-led</span></div>
    <section className="brand-statement public-main"><span className="eyebrow">THE FLESHLAB EDIT</span><p>Real people. Intentional production. A living world of performers, independent creators and full-length stories with something to say.</p><a className="text-link" href="/v3/videos">Explore the catalogue <b aria-hidden="true">↗</b></a></section>
    {data.sections?.featured_videos !== false && <section className="public-section featured-section public-main"><SectionHead eyebrow="SELECTED WORK" title="Featured releases." href="/v3/videos" action="View all films"/><div className="release-layout">{featured.slice(0, 5).map((item, index) => <ReleaseCard key={item.id || item.slug} video={item} lead={index === 0} position={index + 1}/>)}</div>{!featured.length && <div className="public-empty">New published work will appear here.</div>}</section>}
    {data.sections?.new_releases !== false && <section className="release-band"><div className="public-main public-section"><SectionHead eyebrow="JUST RELEASED" title="New releases." href="/v3/videos" action="See the library"/><div className="release-rail">{newReleases.slice(0, 8).map((item, index) => <ReleaseCard key={item.id || item.slug} video={item} position={index + 1}/>)}</div>{!newReleases.length && <div className="public-empty">No new published releases are available yet.</div>}</div></section>}
    {data.sections?.performers !== false && <section className="performer-section public-main public-section"><SectionHead eyebrow="THE PEOPLE BEHIND THE WORK" title="Meet the faces of FLESHLAB." href="/v3/performers" action="All performers"/><div className="performer-rail">{performers.slice(0, 6).map((item, index) => <PerformerCard key={item.id} performer={item} index={index}/>)}</div>{!performers.length && <div className="public-empty">Public performer profiles will appear here.</div>}</section>}
    {performers[0] && <section className="editorial-spotlight public-main"><div className="spotlight-image"><Image record={performers[0]} alt={`Portrait of ${performers[0].display_name}`}/><span className="spotlight-stamp">F / 01</span></div><div className="spotlight-copy"><span className="eyebrow">EDITORIAL SPOTLIGHT</span><h2>{esc(performers[0].display_name)}</h2><p>{esc(performers[0].bio || 'A performer at the centre of the FLESHLAB world.')}</p><a className="public-secondary" href={`/v3/performers/${encodeURIComponent(performers[0].slug)}`}>Enter the profile <span aria-hidden="true">↗</span></a></div></section>}
    {data.sections?.collections !== false && collections.length > 0 && <section className="collection-band"><div className="public-main public-section"><SectionHead eyebrow="CURATED WORLDS" title="Collections with a point of view." href="/v3/collections" action="All collections"/><div className={collections.length === 1 ? 'collection-feature-wrap' : 'collection-grid'}>{collections.length === 1 ? <CollectionCard collection={collections[0]} feature/> : collections.slice(0, 4).map(item => <CollectionCard key={item.id || item.slug} collection={item}/>)}</div></div></section>}
    <section className="brand-story public-main"><div className="story-mark">F<span>/</span>L</div><div><span className="eyebrow">THE STUDIO</span><h2>Made with intention.<br/><i>Watched with feeling.</i></h2><p>FLESHLAB documents real chemistry, real bodies and real stories through independent, creator-led production.</p></div></section>
    {data.sections?.creator_cta !== false && <section className="creator-cta public-main"><div><span className="eyebrow">CREATE WITH FLESHLAB</span><h2>Your work<br/><i>deserves a stage.</i></h2><p>Submit your own content and earn from approved footage through a private, transparent creator experience.</p></div><a className="public-primary" href="https://earn.fleshlab.online">Earn with FLESHLAB <span aria-hidden="true">↗</span></a></section>}
    <section className="final-brand-cta public-main"><span className="eyebrow">THE FULL FLESHLAB WORLD</span><h2>Stay for<br/><i>the story.</i></h2><p>Explore the latest releases, the people behind them and collections made to be watched all the way through.</p><a className="public-primary" href="/v3/videos">Explore the full catalogue <span aria-hidden="true">↗</span></a></section>
  </>}</main></Shell>;
}

function Card({ video }) { return <a className="public-simple-card" href={videoHref(video)}><Image record={video} alt={labelFor(video)}/><CardMeta video={video}/></a>; }
function Grid({ records = [], empty = 'No published records are available.' }) { return records.length ? <div className="public-simple-grid">{records.map(item => <Card video={item} key={item.id || item.slug}/>)}</div> : <div className="public-empty">{empty}</div>; }
function ListingEntity({ item, kind }) { return <a className="public-entity" href={`/v3/${kind}/${encodeURIComponent(item.slug)}`}><Image record={item} alt={item.display_name || item.name}/><span className="eyebrow">{kind.slice(0, -1)}</span><h3>{item.display_name || item.name}</h3><small>{item.video_count ? `${item.video_count} published videos` : item.nationality || item.slug}</small></a>; }
function Listing({ kind }) { const [data, setData] = useState(null); const [q, setQ] = useState(''); const [error, setError] = useState(''); const load = () => get(`/${kind}?q=${encodeURIComponent(q)}&limit=24`).then(setData).catch(e => setError(e.message)); useEffect(load, []); const records = data?.records || []; const label = kind === 'videos' ? 'Videos' : kind === 'performers' ? 'Performers' : 'Brands'; return <Shell seo={{ title: `${label} | FLESHLAB`, description: `Browse published FLESHLAB ${label.toLowerCase()}.` }}><main className="public-main"><section className="public-title"><span className="eyebrow">FLESHLAB / {kind.toUpperCase()}</span><h1>{kind === 'videos' ? 'Published films.' : kind === 'performers' ? 'The performers.' : 'The brands.'}</h1><p>Explore the public FLESHLAB catalogue.</p></section><div className="public-search"><label className="sr-only" htmlFor={`search-${kind}`}>Search {kind}</label><input id={`search-${kind}`} value={q} onChange={event => setQ(event.target.value)} onKeyDown={event => event.key === 'Enter' && load()} placeholder={`Search ${kind}`} /><button onClick={load}>Search</button></div>{error ? <p className="error">{error}</p> : kind === 'videos' ? <Grid records={records}/> : <div className="public-entity-grid">{records.length ? records.map(item => <ListingEntity key={item.id} item={item} kind={kind}/>) : <div className="public-empty">No published records are available.</div>}</div>}</main></Shell>; }
function Detail({ kind, slug }) { const [data, setData] = useState(null); const [error, setError] = useState(''); useEffect(() => { get(`/${kind}/${encodeURIComponent(slug)}`).then(setData).catch(e => setError(e.message)); }, [kind, slug]); if (error) return <Shell seo={{ title: 'Not found | FLESHLAB', description: 'The requested public record was not found.' }}><main className="public-main"><div className="public-state"><div className="public-empty">{error}</div></div></main></Shell>; if (!data) return <Shell seo={{ title: 'Loading | FLESHLAB', description: 'Loading the public FLESHLAB record.' }}><main className="public-main"><div className="public-state"><div className="public-empty">Loading catalogue record…</div></div></main></Shell>; const record = data.record; const video = kind === 'videos'; const title = record.title || record.display_name || record.name; const description = record.description || record.bio || 'Published FLESHLAB catalogue record.'; const image = publicImage(data.assets?.find(asset => asset.type === 'thumbnail')?.url || data.assets?.find(asset => asset.type === 'trailer')?.url || imageFor(record)); return <Shell seo={{ title: `${title} | FLESHLAB`, description, image }}><main className="public-main public-detail"><span className="eyebrow">FLESHLAB / {kind.slice(0, -1).toUpperCase()}</span><h1>{title}</h1><p className="public-lede">{description}</p>{video && <div className="detail-stage">{image ? <img src={image} alt={title}/> : <span>MEDIA PREVIEW</span>}</div>}{!video && <div className="public-section"><SectionHead eyebrow="PUBLISHED CONTENT" title="In the library."/><Grid records={data.videos}/></div>}{video && <><div className="detail-facts"><span>{record.brand_name || 'FLESHLAB'}</span><span>{record.performers?.map(item => item.name).join(' · ') || 'Uncredited'}</span><span>{record.release_date || 'Published catalogue'}</span></div><div className="public-section"><SectionHead title="More from the library."/><Grid records={data.related}/></div></>}</main></Shell>; }
function Collection({ slug }) { const [data, setData] = useState(null); const [error, setError] = useState(''); useEffect(() => { get(`/collections/${encodeURIComponent(slug)}`).then(setData).catch(e => setError(e.message)); }, [slug]); const title = data?.record?.title || 'Collection'; const description = data?.record?.description || 'A curated FLESHLAB collection.'; return <Shell seo={{ title: `${title} | FLESHLAB`, description, image: data?.record?.cover_asset_reference }}><main className="public-main">{error ? <div className="public-state"><div className="public-empty">{error}</div></div> : !data ? <div className="public-state"><div className="public-empty">Loading collection…</div></div> : <><section className="public-title"><span className="eyebrow">COLLECTION</span><h1>{data.record.title}</h1><p>{description}</p></section><Grid records={data.videos}/></>}</main></Shell>; }
function CollectionListing() { const [data, setData] = useState(null); const [error, setError] = useState(''); useEffect(() => { get('/collections').then(setData).catch(e => setError(e.message)); }, []); return <Shell seo={{ title: 'Collections | FLESHLAB', description: 'Curated public FLESHLAB collections.' }}><main className="public-main"><section className="public-title"><span className="eyebrow">FLESHLAB / COLLECTIONS</span><h1>Curated worlds.</h1><p>Public selections from the FLESHLAB catalogue.</p></section>{error ? <p className="error">{error}</p> : <div className="public-entity-grid">{data?.records?.map(item => <CollectionCard key={item.id || item.slug} collection={item}/>)}</div>}</main></Shell>; }
export function PublicApp() { const path = window.location.pathname.replace(/^\/v3\/?/, ''); if (!path) return <BrandHome/>; const parts = path.split('/').filter(Boolean); if (parts[0]==='home') return <BrandHome/>; if (parts[0] === 'catalogue') return <Listing kind="videos"/>; if (parts[0] === 'videos' && parts[1]) return <Detail kind="videos" slug={parts[1]}/>; if (parts[0] === 'performers' && parts[1]) return <Detail kind="performers" slug={parts[1]}/>; if (parts[0] === 'brands' && parts[1]) return <Detail kind="brands" slug={parts[1]}/>; if (parts[0] === 'collections' && parts[1]) return <Collection slug={parts[1]}/>; if (parts[0] === 'collections') return <CollectionListing/>; if (['videos', 'performers', 'brands'].includes(parts[0])) return <Listing kind={parts[0]}/>; return <BrandHome/>; }
