import React, { useEffect, useState } from 'react';
import './public.css';

const get = async path => { const response = await fetch(`/api/v3/public${path}`, { headers: { accept: 'application/json' } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data?.error?.message || 'This page is unavailable.'); return data; };
const esc = value => String(value || '').replace(/[<>]/g, '');
const publicImage = value => /^https?:\/\//i.test(String(value || '')) ? value : undefined;
const imageFor = (record = {}) => publicImage(record.thumbnail_url || record.trailer_url || record.legacy_cover_image_url || record.legacy_profile_image_url || record.legacy_logo_url || record.cover_asset_reference);
const labelFor = (record = {}) => record.title || record.display_name || record.name || 'FLESHLAB';

function Seo({ title, description, image }) {
  useEffect(() => {
    const canonical = `${window.location.origin}${window.location.pathname}`; document.title = title;
    [['name', 'description', description], ['property', 'og:title', title], ['property', 'og:description', description], ['property', 'og:image', publicImage(image)]].forEach(([attribute, name, content]) => { if (!content) return; let element = document.head.querySelector(`meta[${attribute}="${name}"]`); if (!element) { element = document.createElement('meta'); element.setAttribute(attribute, name); document.head.appendChild(element); } element.setAttribute('content', String(content).slice(0, 300)); });
    let link = document.head.querySelector('link[rel="canonical"]'); if (!link) { link = document.createElement('link'); link.rel = 'canonical'; document.head.appendChild(link); } link.href = canonical;
    let schema = document.head.querySelector('#fleshlab-public-schema'); if (!schema) { schema = document.createElement('script'); schema.id = 'fleshlab-public-schema'; schema.type = 'application/ld+json'; document.head.appendChild(schema); } schema.textContent = JSON.stringify({ '@context': 'https://schema.org', '@type': 'WebSite', name: 'FLESHLAB', url: canonical, description: String(description || '').slice(0, 300), ...(publicImage(image) ? { image: publicImage(image) } : {}) });
  }, [title, description, image]); return null;
}

function Shell({ children, seo = {} }) {
  return <div className="public-shell"><Seo title={seo.title || 'FLESHLAB | Independent creator studio'} description={seo.description || 'Creator-led films from FLESHLAB.'} image={seo.image}/><header className="public-nav"><a href="/v3/" className="public-brand" aria-label="FLESHLAB home">FLESH<span>LAB</span><small>STUDIO</small></a><nav aria-label="Public navigation"><a href="/v3/">Home</a><a href="/v3/videos">Videos</a><a href="/v3/performers">Performers</a><a href="/v3/brands">Brands</a><a href="/v3/collections">Collections</a><a className="nav-join" href="/become-performer">Join</a><a href="/v3/?admin=1">Login</a></nav></header>{children}<footer className="public-footer"><div><a className="public-brand" href="/v3/">FLESH<span>LAB</span></a><p>Independent, creator-led production.</p></div><div className="footer-links"><a href="/v3/videos">Catalogue</a><a href="/v3/performers">Performers</a><a href="/v3/brands">Brands</a><a href="/v3/collections">Collections</a><a href="/become-performer">Join as a creator</a></div><div className="footer-links"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/compliance">Compliance</a><a href="mailto:studiosupport@fleshlab.online">Support</a></div><small>© {new Date().getFullYear()} FLESHLAB. Published catalogue only.</small></footer></div>;
}

function Image({ record, alt, eager = false, className = '' }) { const src = imageFor(record); return <div className={`public-image ${className}`}>{src ? <img src={src} alt={alt} loading={eager ? 'eager' : 'lazy'} {...(eager ? { fetchPriority: 'high' } : {})}/> : <span>FLESHLAB</span>}</div>; }
function Card({ video, featured = false }) { return <a className={`public-card ${featured ? 'featured' : ''}`} href={`/v3/videos/${encodeURIComponent(video.slug)}`}><Image record={video} alt={labelFor(video)}/><div className="public-card-meta"><b>{esc(video.title)}</b><small>{video.performers?.map(p => p.name).join(' · ') || video.brand_name || 'FLESHLAB production'}</small></div></a>; }
function Grid({ records = [], empty = 'No published records are available.', featured = false }) { return records.length ? <div className="public-grid">{records.map(item => <Card video={item} featured={featured} key={item.id || item.slug}/>)}</div> : <div className="public-empty">{empty}</div>; }
function SectionHead({ eyebrow, title, href, action = 'View all' }) { return <div className="public-section-head"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{href && <a href={href}>{action} <span aria-hidden="true">↗</span></a>}</div>; }
function PerformerCard({ performer }) { return <a className="performer-card" href={`/v3/performers/${encodeURIComponent(performer.slug)}`}><Image record={performer} alt={performer.display_name}/><div><span className="eyebrow">PERFORMER</span><h3>{esc(performer.display_name)}</h3><p>{esc(performer.bio || performer.nationality || 'Discover the work.')}</p><small>{performer.video_count || 0} published video{performer.video_count === 1 ? '' : 's'} <span aria-hidden="true">↗</span></small></div></a>; }
function CollectionCard({ collection }) { return <a className="collection-card" href={`/v3/collections/${encodeURIComponent(collection.slug)}`}><Image record={{ cover_asset_reference: collection.cover_asset_reference }} alt={collection.title}/><div><span className="eyebrow">COLLECTION</span><h3>{esc(collection.title)}</h3><p>{esc(collection.description || 'A considered FLESHLAB selection.')}</p><small>{collection.video_count || 0} published videos</small></div></a>; }

function Home() {
  const [data, setData] = useState(null); const [error, setError] = useState(''); useEffect(() => { get('/homepage').then(setData).catch(e => setError(e.message)); }, []);
  const hero = data?.hero; const seo = { title: hero?.title ? `${hero.title} | FLESHLAB` : 'FLESHLAB | Independent creator studio', description: hero?.summary || 'Creator-led films, authentic chemistry and a catalogue made with intention.', image: hero?.image };
  return <Shell seo={seo}><main className="public-home">{error ? <div className="public-main"><p className="error">{error}</p></div> : !data ? <div className="public-main"><div className="public-empty">Loading the studio…</div></div> : <>
    <section className="home-hero">{hero?.image && <img className="hero-media" src={publicImage(hero.image)} alt="" fetchPriority="high"/>}<div className="hero-grain"/><div className="hero-content"><span className="eyebrow">{hero?.eyebrow || 'FLESHLAB / INDEPENDENT STUDIO'}</span><h1>{esc(hero?.title || 'Stories with presence.')}</h1><p>{esc(hero?.summary || 'Creator-led films, real chemistry and a catalogue made with intention.')}</p><div className="public-actions"><a className="public-primary" href={hero?.cta_target || '/v3/videos'}>{hero?.cta_label || 'Explore videos'} <span aria-hidden="true">↗</span></a><a className="public-secondary" href="/v3/performers">Meet the performers</a></div>{hero?.record && <a className="hero-credit" href={hero.kind === 'performer' ? `/v3/performers/${hero.record.slug}` : hero.kind === 'collection' ? `/v3/collections/${hero.record.slug}` : `/v3/videos/${hero.record.slug}`}>{hero.kind === 'performer' ? 'In focus' : hero.kind === 'collection' ? 'Featured collection' : 'Featured film'} · {labelFor(hero.record)}</a>}</div></section>
    <section className="brand-statement public-main"><span className="eyebrow">THE FLESHLAB EDIT</span><p>Real people. Intentional production. A growing world of Asian talent, independent creators and full-length stories with something to say.</p></section>
    {data.sections?.featured_videos !== false && <section className="public-section public-main"><SectionHead eyebrow="SELECTED WORK" title="Featured films." href="/v3/videos"/><Grid records={data.featured_videos} empty="New published work will appear here." featured/></section>}
    {data.sections?.new_releases !== false && <section className="release-band"><div className="public-main"><SectionHead eyebrow="JUST RELEASED" title="New in the library." href="/v3/collections/new-releases" action="See new releases"/><Grid records={data.new_releases}/></div></section>}
    {data.sections?.performers !== false && <section className="public-section public-main"><SectionHead eyebrow="FACES OF FLESHLAB" title="Meet the performers." href="/v3/performers"/><div className="performer-grid">{data.featured_performers?.map(item => <PerformerCard key={item.id} performer={item}/>)}</div></section>}
    {data.sections?.collections !== false && data.featured_collections?.length > 0 && <section className="collection-band"><div className="public-main"><SectionHead eyebrow="CURATED WORLDS" title="Collections with a point of view." href="/v3/collections"/><div className="collection-grid">{data.featured_collections.map(item => <CollectionCard key={item.id || item.slug} collection={item}/>)}</div></div></section>}
    {data.sections?.creator_cta !== false && <section className="creator-cta public-main"><div><span className="eyebrow">CREATE WITH FLESHLAB</span><h2>Bring your story into focus.</h2><p>Professional production, private onboarding and a creator-first environment for people ready to build something real.</p></div><a className="public-primary" href="/become-performer">Join FLESHLAB <span aria-hidden="true">↗</span></a></section>}
    {data.sections?.trust !== false && <section className="trust-strip public-main" aria-label="FLESHLAB studio principles"><article><span>01</span><b>Creator-led</b><p>People stay at the centre of the work.</p></article><article><span>02</span><b>Consent-aware</b><p>Professional workflows support every production.</p></article><article><span>03</span><b>Independent</b><p>A studio world built with intention.</p></article></section>}
  </>}</main></Shell>;
}

function Listing({ kind }) { const [data,setData]=useState(null); const [q,setQ]=useState(''); const [error,setError]=useState(''); const load=()=>get(`/${kind}?q=${encodeURIComponent(q)}&limit=24`).then(setData).catch(e=>setError(e.message)); useEffect(load,[]); const records=data?.records||[]; const label=kind === 'videos' ? 'Videos' : kind === 'performers' ? 'Performers' : 'Brands'; return <Shell seo={{title:`${label} | FLESHLAB`,description:`Browse published FLESHLAB ${label.toLowerCase()}.`}}><main className="public-main"><section className="public-title"><span className="eyebrow">FLESHLAB / {kind.toUpperCase()}</span><h1>{kind === 'videos' ? 'Published films.' : kind === 'performers' ? 'The performers.' : 'The brands.'}</h1><p>Explore the public FLESHLAB catalogue.</p></section><div className="public-search"><label className="sr-only" htmlFor={`search-${kind}`}>Search {kind}</label><input id={`search-${kind}`} value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder={`Search ${kind}`}/><button onClick={load}>Search</button></div>{error?<p className="error">{error}</p>:kind==='videos'?<Grid records={records}/>:<div className="public-entity-grid">{records.length?records.map(item=><a className="public-entity" key={item.id} href={`/v3/${kind}/${encodeURIComponent(item.slug)}`}><Image record={item} alt={item.display_name||item.name}/><span className="eyebrow">{kind.slice(0,-1)}</span><h3>{item.display_name||item.name}</h3><small>{item.video_count ? `${item.video_count} published videos` : item.nationality || item.slug}</small></a>):<div className="public-empty">No published records are available.</div>}</div>}</main></Shell>; }
function Detail({ kind, slug }) { const [data,setData]=useState(null); const [error,setError]=useState(''); useEffect(()=>{get(`/${kind}/${encodeURIComponent(slug)}`).then(setData).catch(e=>setError(e.message));},[kind,slug]); if(error)return <Shell seo={{title:'Not found | FLESHLAB',description:'The requested public record was not found.'}}><main className="public-main"><div className="public-empty">{error}</div></main></Shell>; if(!data)return <Shell seo={{title:'Loading | FLESHLAB',description:'Loading the public FLESHLAB record.'}}><main className="public-main"><div className="public-empty">Loading catalogue record…</div></main></Shell>; const r=data.record; const video=kind==='videos'; const title=r.title||r.display_name||r.name; const description=r.description||r.bio||'Published FLESHLAB catalogue record.'; const image=publicImage(data.assets?.find(a=>a.type==='thumbnail')?.url||data.assets?.find(a=>a.type==='trailer')?.url||imageFor(r)); return <Shell seo={{title:`${title} | FLESHLAB`,description,image}}><main className="public-main public-detail"><span className="eyebrow">FLESHLAB / {kind.slice(0,-1).toUpperCase()}</span><h1>{title}</h1><p className="public-lede">{description}</p>{video&&<div className="detail-stage">{image?<img src={image} alt={title}/>:<span>MEDIA PREVIEW</span>}</div>} {!video&&<div className="public-section"><SectionHead eyebrow="PUBLISHED CONTENT" title="In the library."/><Grid records={data.videos}/></div>}{video&&<><div className="detail-facts"><span>{r.brand_name||'FLESHLAB'}</span><span>{r.performers?.map(p=>p.name).join(' · ')||'Uncredited'}</span><span>{r.release_date||'Published catalogue'}</span></div><div className="public-section"><SectionHead title="More from the library."/><Grid records={data.related}/></div></>}</main></Shell>; }
function Collection({ slug }) { const [data,setData]=useState(null); const [error,setError]=useState(''); useEffect(()=>{get(`/collections/${encodeURIComponent(slug)}`).then(setData).catch(e=>setError(e.message));},[slug]); const title=data?.record?.title||'Collection'; const description=data?.record?.description||'A curated FLESHLAB collection.'; return <Shell seo={{title:`${title} | FLESHLAB`,description,image:data?.record?.cover_asset_reference}}><main className="public-main">{error?<div className="public-empty">{error}</div>:!data?<div className="public-empty">Loading collection…</div>:<><section className="public-title"><span className="eyebrow">COLLECTION</span><h1>{data.record.title}</h1><p>{description}</p></section><Grid records={data.videos}/></>}</main></Shell>; }
function CollectionListing() { const [data,setData]=useState(null); const [error,setError]=useState(''); useEffect(()=>{get('/collections').then(setData).catch(e=>setError(e.message));},[]); return <Shell seo={{title:'Collections | FLESHLAB',description:'Curated public FLESHLAB collections.'}}><main className="public-main"><section className="public-title"><span className="eyebrow">FLESHLAB / COLLECTIONS</span><h1>Curated worlds.</h1><p>Public selections from the FLESHLAB catalogue.</p></section>{error?<p className="error">{error}</p>:<div className="collection-grid">{data?.records?.map(item=><CollectionCard key={item.id||item.slug} collection={item}/>)}</div>}</main></Shell>; }
export function PublicApp() { const path=window.location.pathname.replace(/^\/v3\/?/,''); if(!path)return <Home/>; const parts=path.split('/').filter(Boolean); if(parts[0]==='catalogue')return <Listing kind="videos"/>; if(parts[0]==='videos'&&parts[1])return <Detail kind="videos" slug={parts[1]}/>; if(parts[0]==='performers'&&parts[1])return <Detail kind="performers" slug={parts[1]}/>; if(parts[0]==='brands'&&parts[1])return <Detail kind="brands" slug={parts[1]}/>; if(parts[0]==='collections'&&parts[1])return <Collection slug={parts[1]}/>; if(parts[0]==='collections')return <CollectionListing/>; if(['videos','performers','brands'].includes(parts[0]))return <Listing kind={parts[0]}/>; return <Home/>; }
