import { Maximize2, Rocket, Send, Target, Users, X } from "lucide-react";
import { useState } from "react";

export default function ProducerPanel({ recommendations = [], briefing, mission, library = [], messages = [], busy, hidden, onAsk, onAction, onExpand, onClose }) {
  const [text, setText] = useState("");
  if (hidden) return <button type="button" className="flos-ai-reopen" onClick={onExpand}>Open AI Producer</button>;
  const icons = [Target, Users, Rocket];
  const items = recommendations.slice(0,3);
  const prompts = [mission?.title && `Why this mission: ${mission.title}?`, "Explain today’s plan", "How can I earn more this week?", library[0]?.value && `Review missing content: ${library[0].value}`, items[0]?.title && `Turn this recommendation into a mission: ${items[0].title}`].filter(Boolean).slice(0,5);
  const submit = (value = text) => { const prompt = String(value || "").trim(); if (!prompt || busy) return; setText(""); onAsk?.(prompt); };
  return <aside id="ai" className="flos-producer"><header><button type="button" onClick={onExpand}><b>AI PRODUCER</b></button><span><button type="button" aria-label="Expand AI Producer" onClick={onExpand}><Maximize2 /></button><button type="button" aria-label="Close AI Producer" onClick={onClose}><X /></button></span></header><div className="flos-ai-core"><span>AI</span><b>{items.length || 0}</b></div><p>{briefing?.headline || "Your AI Producer is collecting creator signals."}<br />{briefing?.summary || "Recommendations appear only after Creator OS has enough live evidence."}</p><div className="flos-ai-list">{items.length ? items.map((rec,i) => { const Icon = icons[i] || Target; return <article key={rec.id || rec.title}><button type="button" aria-label={`Open recommendation ${rec.title}`} onClick={() => onAction?.("view", rec)}><Icon /></button><span><b>{rec.title}</b>{rec.recommendation}</span><div className="flos-rec-actions"><button type="button" onClick={() => onAction?.("convert_to_mission", rec)}>Mission</button><button type="button" onClick={() => onAction?.("save", rec)}>Save</button><button type="button" onClick={() => onAction?.("dismiss", rec)}>Dismiss</button></div></article>; }) : <article><Target /><span>No active recommendation yet. Upload history, fan behaviour and revenue patterns are being analysed.</span></article>}</div><div className="flos-prompts"><small>Ask from today’s data...</small>{prompts.length ? prompts.map(x => <button type="button" disabled={busy} key={x} onClick={() => submit(x)}>{x}</button>) : <p className="flos-empty">Quick actions appear when Creator OS has mission, library or recommendation data.</p>}</div><div className="flos-ai-chat">{messages.map((msg, i) => <p key={`${msg.role}-${i}`} className={msg.role === "assistant" ? "answer" : "question"}>{msg.text}</p>)}{busy && <p className="answer">AI Producer is reading your creator context…</p>}</div><form onSubmit={(event) => { event.preventDefault(); submit(); }}><label><input aria-label="Message your AI Producer" value={text} onChange={(event) => setText(event.target.value)} disabled={busy} placeholder="Message your producer..." /><button type="submit" aria-label="Send message" disabled={busy || !text.trim()}><Send /></button></label></form></aside>;
}