function clamp(value, min = 0, max = 1) {
  return Math.max(min, Math.min(max, value));
}

function textFrom(metadata = {}) {
  return [metadata.videoTitle, metadata.optionalSubtitle, metadata.campaignName, metadata.contentType, metadata.performerName]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();
}

const LANGUAGES = {
  vacation: {
    id: "vacation-lifestyle",
    temperature: "warm",
    energy: "open_cinematic",
    contrast_style: "sunlit_subject_against_controlled_brand_zone",
    lighting_style: "warm_haze",
    color_strategy: "natural_skin_beach_warmth_with_brand_red_memory",
    texture_density: 0.18,
    typography_style: "wide_cinematic",
    poster_density: 0.44,
    negative_space_strategy: "open_breathing_lifestyle_space",
    camera_feeling: "aspirational_lifestyle",
    graphic_aggression: 0.36,
    brand_expression: "clean_confident_signature",
    thumbnail_priority: "promise_environment_performer",
    emotional_intensity: 0.62,
    atmosphere: "warm-haze",
    family_bias: ["hero-poster", "premium-poster", "movie-poster"],
    titleFont: "Bebas Neue",
    accentFont: "Inter",
    titleScaleMultiplier: 0.96,
    cropZoomMultiplier: 0.96,
    designZoneWidth: 0.36,
    darkness: 0.58,
    redIntensity: 0.24,
    saturation: 1.08,
    brightness: 1.06,
    contrast: 1.08,
  },
  danger: {
    id: "claustrophobic-danger",
    temperature: "hot_dark",
    energy: "high_tension",
    contrast_style: "hard_shadow_neon_separation",
    lighting_style: "dirty_neon_edges",
    color_strategy: "black_red_skin_under_pressure",
    texture_density: 0.78,
    typography_style: "compressed_bold",
    poster_density: 0.78,
    negative_space_strategy: "tight_controlled_pressure",
    camera_feeling: "close_private",
    graphic_aggression: 0.9,
    brand_expression: "aggressive_red_stamp",
    thumbnail_priority: "danger_title_performer",
    emotional_intensity: 0.88,
    atmosphere: "danger-red",
    family_bias: ["dark-poster", "action-poster", "commercial-thumbnail"],
    titleFont: "Bebas Neue",
    accentFont: "Permanent Marker",
    titleScaleMultiplier: 1.14,
    cropZoomMultiplier: 1.18,
    designZoneWidth: 0.43,
    darkness: 0.88,
    redIntensity: 0.74,
    saturation: 1.1,
    brightness: 0.86,
    contrast: 1.28,
  },
  luxury: {
    id: "premium-luxury",
    temperature: "warm_quiet",
    energy: "restrained",
    contrast_style: "soft_high_value_separation",
    lighting_style: "controlled_bloom",
    color_strategy: "skin_warm_gold_black",
    texture_density: 0.08,
    typography_style: "minimal_elegant",
    poster_density: 0.34,
    negative_space_strategy: "premium_silence",
    camera_feeling: "polished_studio",
    graphic_aggression: 0.18,
    brand_expression: "quiet_luxury_mark",
    thumbnail_priority: "performer_value_brand",
    emotional_intensity: 0.5,
    atmosphere: "soft-bloom",
    family_bias: ["premium-poster", "minimal-poster", "emotional-poster"],
    titleFont: "Inter",
    accentFont: "Inter",
    titleScaleMultiplier: 0.78,
    cropZoomMultiplier: 1.02,
    designZoneWidth: 0.32,
    darkness: 0.48,
    redIntensity: 0.12,
    saturation: 0.96,
    brightness: 1.04,
    contrast: 1.02,
  },
  documentary: {
    id: "honest-documentary",
    temperature: "bright_human",
    energy: "authentic",
    contrast_style: "clean_editorial",
    lighting_style: "available_light",
    color_strategy: "natural_honest_low_effect",
    texture_density: 0.12,
    typography_style: "neutral_editorial",
    poster_density: 0.38,
    negative_space_strategy: "large_breathing_human_space",
    camera_feeling: "observed_real_moment",
    graphic_aggression: 0.24,
    brand_expression: "trustworthy_editorial",
    thumbnail_priority: "human_authenticity_promise",
    emotional_intensity: 0.48,
    atmosphere: "documentary-air",
    family_bias: ["story-poster", "emotional-poster", "minimal-poster"],
    titleFont: "Inter",
    accentFont: "Inter",
    titleScaleMultiplier: 0.84,
    cropZoomMultiplier: 0.98,
    designZoneWidth: 0.34,
    darkness: 0.5,
    redIntensity: 0.12,
    saturation: 0.98,
    brightness: 1.05,
    contrast: 1.04,
  },
  celebration: {
    id: "fan-celebration",
    temperature: "hot_bright",
    energy: "celebratory",
    contrast_style: "bold_social_pop",
    lighting_style: "bright_event_energy",
    color_strategy: "brand_red_high_energy_social_proof",
    texture_density: 0.44,
    typography_style: "bold_social",
    poster_density: 0.68,
    negative_space_strategy: "active_but_readable",
    camera_feeling: "event_campaign",
    graphic_aggression: 0.68,
    brand_expression: "loud_community_stamp",
    thumbnail_priority: "social_proof_title_brand",
    emotional_intensity: 0.78,
    atmosphere: "celebration-red",
    family_bias: ["commercial-thumbnail", "action-poster", "editorial-poster"],
    titleFont: "Bebas Neue",
    accentFont: "Permanent Marker",
    titleScaleMultiplier: 1.08,
    cropZoomMultiplier: 1.06,
    designZoneWidth: 0.41,
    darkness: 0.66,
    redIntensity: 0.58,
    saturation: 1.18,
    brightness: 1,
    contrast: 1.18,
  },
  raw: {
    id: "raw-amateur-impact",
    temperature: "hot_raw",
    energy: "unpolished_direct",
    contrast_style: "rough_high_contrast",
    lighting_style: "imperfect_flash_or_available_light",
    color_strategy: "skin_red_black_grit",
    texture_density: 0.68,
    typography_style: "distressed_heavy",
    poster_density: 0.72,
    negative_space_strategy: "rough_controlled_zone",
    camera_feeling: "immediate_amateur",
    graphic_aggression: 0.76,
    brand_expression: "raw_studio_stamp",
    thumbnail_priority: "raw_promise_performer",
    emotional_intensity: 0.76,
    atmosphere: "raw-grit",
    family_bias: ["commercial-thumbnail", "editorial-poster", "dark-poster"],
    titleFont: "Bebas Neue",
    accentFont: "Permanent Marker",
    titleScaleMultiplier: 1.1,
    cropZoomMultiplier: 1.1,
    designZoneWidth: 0.42,
    darkness: 0.74,
    redIntensity: 0.6,
    saturation: 1.06,
    brightness: 0.94,
    contrast: 1.24,
  },
};

const DEFAULT_LANGUAGE = {
  id: "commercial-key-art",
  temperature: "brand_hot",
  energy: "confident",
  contrast_style: "brand_readability_first",
  lighting_style: "cinematic_subject_separation",
  color_strategy: "black_white_red_brand_memory",
  texture_density: 0.42,
  typography_style: "bold_commercial",
  poster_density: 0.58,
  negative_space_strategy: "protected_promise_zone",
  camera_feeling: "campaign_key_art",
  graphic_aggression: 0.58,
  brand_expression: "strong_brand_ownership",
  thumbnail_priority: "promise_brand_performer",
  emotional_intensity: 0.66,
  atmosphere: "brand-red",
  family_bias: ["commercial-thumbnail", "hero-poster", "editorial-poster"],
  titleFont: "Bebas Neue",
  accentFont: "Permanent Marker",
  titleScaleMultiplier: 1,
  cropZoomMultiplier: 1,
  designZoneWidth: 0.39,
  darkness: 0.7,
  redIntensity: 0.46,
  saturation: 1.06,
  brightness: 1,
  contrast: 1.14,
};

function chooseLanguage(metadata, analysis) {
  const text = textFrom(metadata);
  if (/beach|escape|summer|island|outdoor|travel|vacation|cebu|sea|pool/.test(text)) return LANGUAGES.vacation;
  if (/hotel|bareback|night|secret|forbidden|private|dark|room|danger/.test(text)) return LANGUAGES.danger;
  if (/massage|spa|luxury|premium|vip|suite|gentle|sensual/.test(text)) return LANGUAGES.luxury;
  if (/first|debut|documentary|behind|real|honest|story/.test(text)) return LANGUAGES.documentary;
  if (/fan favorite|favorite|fans|celebration|popular|viral|community/.test(text)) return LANGUAGES.celebration;
  if (/raw|amateur|uncut|rough|wild|homemade/.test(text)) return LANGUAGES.raw;
  if ((analysis?.brightness || 0.5) < 0.36) return LANGUAGES.danger;
  return DEFAULT_LANGUAGE;
}

export function inferGraphicLanguage(metadata = {}, analysis = {}) {
  const language = { ...DEFAULT_LANGUAGE, ...chooseLanguage(metadata, analysis) };
  const specificity = language.id === DEFAULT_LANGUAGE.id ? 0.58 : 0.86;
  const visualFit = clamp((analysis.thumbnailImpact || 0.55) * 0.28 + (analysis.sceneReadability || 0.55) * 0.22 + (analysis.visualCuriosity || 0.55) * 0.18 + specificity * 0.32);
  return {
    ...language,
    score: Math.round(visualFit * 100),
    strength: visualFit,
    validation: {
      canSpeakWithoutText: visualFit >= 0.58,
      emotionalGenreWithin500ms: language.id !== DEFAULT_LANGUAGE.id || visualFit >= 0.66,
      failures: [
        ...(visualFit < 0.58 ? ["graphic language too weak without title"] : []),
        ...(language.id === DEFAULT_LANGUAGE.id && visualFit < 0.66 ? ["commercial promise did not select a distinct visual identity"] : []),
      ],
    },
  };
}

export function applyGraphicLanguageToFamily(family, graphicLanguage) {
  if (!family || !graphicLanguage) return family;
  return {
    ...family,
    graphicLanguage,
    cropZoom: (family.cropZoom || 1) * (graphicLanguage.cropZoomMultiplier || 1),
    treatment: graphicLanguage.atmosphere || family.treatment,
    typography: {
      ...family.typography,
      titleFont: graphicLanguage.titleFont || family.typography?.titleFont,
      accentFont: graphicLanguage.accentFont || family.typography?.accentFont,
      titleScale: (family.typography?.titleScale || 0.08) * (graphicLanguage.titleScaleMultiplier || 1),
    },
  };
}