import { Users, ShieldCheck, CreditCard, Headphones, Globe2, Wallet, Play, Clapperboard, Handshake, UserPlus, Lock, CloudUpload, CheckCircle2, DollarSign, Lightbulb, Camera, Crown, BadgeCheck, ChevronRight, Dumbbell, BedDouble, Plane, GraduationCap, Home, Building2 } from "lucide-react";
import LanguageSwitcher from "@/components/public/LanguageSwitcher";
import MediaImage from "@/components/homeTube/MediaImage";
import { buildPublicAssetUrl } from "@/lib/videoAssetResolver";

const HERO_IMAGE = "https://media.base44.com/images/public/6a1bc26018a7bec38bc6ac4a/e78322bac_generated_image.png";
const SELFIE_IMAGE = "https://media.base44.com/images/public/6a1bc26018a7bec38bc6ac4a/867ee06e6_generated_image.png";
const PRODUCTION_IMAGE = "https://media.base44.com/images/public/6a1bc26018a7bec38bc6ac4a/2e99b354f_generated_image.png";
const FAN_IMAGE = "https://media.base44.com/images/public/6a1bc26018a7bec38bc6ac4a/1dacb8793_generated_image.png";
const WORLD_IMAGES = [HERO_IMAGE, "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=700&q=80", "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=700&q=80", "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=700&q=80", PRODUCTION_IMAGE, SELFIE_IMAGE];

const navItems = ["WHO WE ARE", "HOW IT WORKS", "EARN MONEY", "VIDEOS", "FAN PRODUCTIONS", "BLOG", "TRUST CENTER"];
const trustItems = [[Users, "100% AMATEUR", "Real people. No actors."], [ShieldCheck, "SAFE & PRIVATE", "Your privacy is 100% protected."], [CreditCard, "FAIR PAY", "Weekly payouts. Always on time."], [Headphones, "FULL SUPPORT", "We guide you from day one."], [Globe2, "GLOBAL COMMUNITY", "Fans from over 120 countries."]];
const paths = [[Wallet, "EARN MONEY", "Turn your life into income. We show you how.", "/become-performer", SELFIE_IMAGE], [Play, "WATCH VIDEOS", "Real amateur content. Updated daily. No fakes.", "/videos", HERO_IMAGE], [Clapperboard, "JOIN A PRODUCTION", "Be part of a story. We handle the rest. You shine.", "/fan-productions", PRODUCTION_IMAGE], [Handshake, "PARTNER WITH US", "Distribute. Collaborate. Monetize premium amateur content.", "#partners", PRODUCTION_IMAGE]];
const journey = [[UserPlus, "JOIN", "Create your account in minutes."], [Lock, "VERIFY", "We protect your identity."], [CloudUpload, "UPLOAD", "Use your smartphone. We accept all content."], [CheckCircle2, "APPROVAL", "Our team reviews within 24–48h."], [Clapperboard, "PUBLISHED", "Your content goes live on the platform."], [DollarSign, "EARN", "Get paid weekly. Keep growing."]];
const worlds = [[BedDouble, "HOTEL\nSESSIONS"], [Plane, "BEACH\nESCAPE"], [Dumbbell, "GYM &\nFITNESS"], [Building2, "MASSAGE\nROOMS"], [GraduationCap, "STUDENT\nLIFE"], [Home, "HOME\nMADE"]];
const trustCenter = [[ShieldCheck, "IDENTITY PROTECTION", "We verify all performers. Your privacy is guaranteed."], [Wallet, "SECURE PAYMENTS", "Encrypted & secure payment system."], [CreditCard, "LEGAL CONTRACTS", "Fair contracts. Clear rights."], [BadgeCheck, "CONTENT PROTECTION", "We protect your content and your rights."], [Users, "18+ ONLY", "All performers are 18+ verified."]];

function Logo({ small = false }) {
  return <a href="/" className="leading-none"><div className={`${small ? "text-[22px]" : "text-[34px]"} font-black tracking-[-0.065em] text-white`}>FLESH<span className="text-[#f0183d]">LAB</span></div><div className="mt-0.5 text-[8px] font-black uppercase tracking-[0.55em] text-white/80">Amateur wins.</div></a>;
}

function ThumbStack({ performers }) {
  const fallback = [SELFIE_IMAGE, HERO_IMAGE, PRODUCTION_IMAGE, FAN_IMAGE, SELFIE_IMAGE];
  const visible = performers.slice(0, 5);
  const thumbs = visible.length ? visible.map((p) => buildPublicAssetUrl(p.profile_image_url || p.cover_image_url)) : fallback;
  return <div className="flex items-center gap-4"><div className="flex -space-x-2">{thumbs.map((src, index) => <img key={src || index} src={src} alt="FLESHLAB creator" className="h-8 w-8 rounded-full border-2 border-[#06090b] object-cover" loading="lazy" />)}</div><p className="text-[9px] leading-4 text-white/62">Join creators from<br /><span className="text-white">120+ countries.</span></p></div>;
}

export default function FleshlabLandingV2({ performers = [] }) {
  return (
    <div className="min-h-screen bg-[#030608] text-white">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#030608]/86 backdrop-blur-xl">
        <div className="mx-auto flex h-[52px] max-w-[1360px] items-center justify-between px-5 lg:px-7">
          <Logo small />
          <nav className="hidden items-center gap-7 lg:flex">{navItems.map((item) => <a key={item} href="#" className="text-[9px] font-black uppercase tracking-[0.09em] text-white/86 hover:text-[#f0183d]">{item}</a>)}</nav>
          <div className="flex items-center gap-3"><LanguageSwitcher /><a href="/become-performer" className="rounded bg-[#f0183d] px-5 py-2.5 text-[9px] font-black uppercase tracking-wide text-white hover:bg-[#ff3152]">JOIN NOW</a></div>
        </div>
      </header>

      <main className="pt-[52px]">
        <section className="relative overflow-hidden border-b border-white/8 bg-black">
          <div className="absolute inset-0"><MediaImage src={HERO_IMAGE} alt="FLESHLAB hotel creator" className="h-full w-full object-cover object-[62%_38%] opacity-95 brightness-[0.82] saturate-[0.92]" /><div className="absolute inset-0 bg-[linear-gradient(90deg,#040709_0%,rgba(4,7,9,0.92)_27%,rgba(4,7,9,0.16)_58%,rgba(4,7,9,0.7)_100%)]" /><div className="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-[#040709] to-transparent" /></div>
          <div className="relative mx-auto grid min-h-[492px] max-w-[1360px] grid-cols-1 px-5 py-8 lg:grid-cols-[1fr_260px] lg:px-7">
            <div className="flex max-w-[470px] flex-col justify-center">
              <h1 className="fl-condensed text-[58px] uppercase leading-[0.86] tracking-[-0.035em] md:text-[72px] lg:text-[80px]">YOUR STORY.<br />YOUR BODY.<br /><span className="text-[#f0183d]">YOUR INCOME.</span></h1>
              <p className="mt-4 max-w-sm text-[14px] leading-6 text-white/86">The #1 platform for Asian amateur performers. Safe. Fair. Profitable.</p>
              <div className="mt-6 flex gap-3"><a href="/become-performer" className="w-[178px] rounded bg-[#f0183d] py-3 text-center text-[10px] font-black uppercase tracking-wide">I WANT TO EARN</a><a href="/videos" className="w-[178px] rounded border border-white/45 bg-black/25 py-3 text-center text-[10px] font-black uppercase tracking-wide">I WANT TO WATCH</a></div>
              <div className="mt-12"><ThumbStack performers={performers} /></div>
            </div>
            <aside className="hidden items-center justify-end lg:flex"><div className="w-[202px] space-y-4 rounded border border-white/14 bg-black/42 p-5 backdrop-blur-sm">{[[Users, "17+", "ACTIVE PERFORMERS"], [Play, "300+", "VIDEOS ONLINE"], [Users, "50K+", "REGISTERED FANS"], [Globe2, "120+", "COUNTRIES"]].map(([Icon, value, label]) => <div key={label} className="flex items-center gap-4"><Icon className="h-6 w-6 text-[#f0183d]" /><div><div className="text-2xl font-black leading-none text-[#f0183d]">{value}</div><div className="mt-1 text-[9px] font-black uppercase text-white/82">{label}</div></div></div>)}</div></aside>
          </div>
        </section>

        <section className="border-b border-white/8 bg-[#080e11]"><div className="mx-auto grid max-w-[1360px] gap-4 px-5 py-4 md:grid-cols-5 lg:px-7">{trustItems.map(([Icon, title, body]) => <div key={title} className="flex gap-3"><Icon className="h-6 w-6 shrink-0 text-[#f0183d]" /><div><h3 className="text-[10px] font-black uppercase">{title}</h3><p className="mt-1 text-[9px] leading-4 text-white/54">{body}</p></div></div>)}</div></section>

        <section className="mx-auto max-w-[1360px] px-5 py-6 lg:px-7"><div className="mb-4 text-center"><h2 className="fl-condensed text-[34px] uppercase leading-none tracking-[0.02em] text-white/78">CHOOSE <span className="text-[#f0183d]">YOUR</span> PATH</h2><p className="text-[9px] text-white/48">What brings you here?</p></div><div className="grid gap-4 md:grid-cols-4">{paths.map(([Icon, title, body, href, image]) => <a key={title} href={href} className="group relative min-h-[174px] overflow-hidden rounded border border-white/13 bg-[#0a1115] p-5"><MediaImage src={image} alt={title} className="absolute inset-0 h-full w-full object-cover opacity-50 transition group-hover:scale-105 group-hover:opacity-62" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/45 to-black/10" /><div className="relative"><div className="mb-9 flex h-14 w-14 items-center justify-center rounded-full border border-[#f0183d] text-[#f0183d]"><Icon className="h-7 w-7" /></div><h3 className="fl-condensed text-[31px] uppercase leading-none tracking-[-0.02em]">{title}</h3><p className="mt-2 max-w-[220px] text-[10px] leading-4 text-white/72">{body}</p><ChevronRight className="absolute bottom-0 right-0 h-5 w-5 transition group-hover:translate-x-1" /></div></a>)}</div></section>

        <section className="relative border-t border-white/8 bg-[#05090c]"><div className="mx-auto grid max-w-[1360px] gap-8 px-5 py-8 lg:grid-cols-[1fr_350px] lg:px-7"><div><h2 className="fl-condensed text-[38px] uppercase leading-none tracking-[-0.02em] text-white/88">YOUR <span className="text-[#f0183d]">JOURNEY</span> AS A CREATOR</h2><p className="mb-7 text-[10px] text-white/48">Simple steps. Real support. Real income.</p><div className="grid gap-3 md:grid-cols-6">{journey.map(([Icon, title, body], index) => <div key={title} className="relative text-center before:absolute before:left-[72%] before:top-8 before:hidden before:h-px before:w-12 before:border-t before:border-dashed before:border-white/22 md:before:block last:before:hidden"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full border border-[#f0183d] text-[#f0183d]"><Icon className="h-7 w-7" /></div><div className="mt-2 text-[10px] font-black text-[#f0183d]">{index + 1}</div><h3 className="text-[11px] font-black uppercase">{title}</h3><p className="mx-auto mt-1 max-w-[94px] text-[8px] leading-4 text-white/50">{body}</p></div>)}</div><a href="/become-performer" className="mx-auto mt-7 flex w-fit items-center gap-8 rounded border border-[#f0183d] px-7 py-2 text-[9px] font-black uppercase text-white/84">LEARN MORE ABOUT BECOMING A PERFORMER <ChevronRight className="h-4 w-4" /></a></div><div className="flex items-center gap-5"><MediaImage src={SELFIE_IMAGE} alt="Creator testimonial" className="h-64 w-48 rounded object-cover object-top" /><blockquote className="text-sm leading-6 text-white/84"><span className="text-5xl leading-none text-[#f0183d]">“</span><br />FLESHLAB changed my life. I film when I want, where I want — and I earn more than I ever did.<br /><br /><span className="font-black text-[#f0183d]">– KAI, 23</span><br /><span className="text-white/45">Performer</span></blockquote></div></div></section>

        <section className="border-t border-white/8 bg-[#05090c]"><div className="mx-auto max-w-[1360px] px-5 py-7 lg:px-7"><h2 className="fl-condensed text-[38px] uppercase leading-none tracking-[-0.02em] text-white/88">EXPLORE <span className="text-[#f0183d]">THEIR</span> WORLDS</h2><p className="mb-4 text-[10px] text-white/48">Different places. Different stories. Same authenticity.</p><div className="grid grid-cols-2 gap-3 md:grid-cols-[repeat(6,1fr)_1.7fr]">{worlds.map(([Icon, label], index) => <a key={label} href="/videos" className="group relative h-[122px] overflow-hidden rounded border border-white/12 bg-[#111]"><MediaImage src={WORLD_IMAGES[index]} alt={label} className="absolute inset-0 h-full w-full object-cover opacity-64 transition group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/35 to-transparent" /><div className="absolute inset-x-0 top-8 text-center"><Icon className="mx-auto h-7 w-7 text-white/85" /></div><div className="absolute inset-x-0 bottom-2 p-2 text-center"><h3 className="text-[13px] font-black uppercase leading-tight whitespace-pre-line">{label}</h3></div></a>)}<div className="relative hidden h-[122px] overflow-hidden rounded border border-[#f0183d]/20 bg-[#12060a] md:block"><MediaImage src={FAN_IMAGE} alt="Your idea our studio" className="absolute inset-0 h-full w-full object-cover opacity-70" /><div className="absolute inset-0 bg-gradient-to-r from-black/25 to-[#100408]/72" /><p className="absolute right-5 top-8 text-right text-[15px] font-black uppercase leading-5 text-[#f0183d]">YOUR IDEA<br />OUR STUDIO<br />YOUR STORY</p></div></div></div></section>

        <section className="border-y border-[#f0183d]/28 bg-[radial-gradient(circle_at_78%_50%,rgba(240,24,61,0.26),transparent_34%),#110509]"><div className="mx-auto grid max-w-[1360px] gap-7 px-5 py-6 md:grid-cols-[310px_1fr_390px] lg:px-7"><div><h2 className="fl-condensed text-[34px] uppercase leading-none tracking-[-0.02em]">FAN PRODUCTIONS</h2><p className="text-lg font-black uppercase text-white/82">Ideas become reality.</p><p className="mt-1 text-[10px] text-white/58">You bring the idea. We help you make it happen.</p><a href="/fan-productions" className="mt-6 inline-flex items-center gap-10 rounded bg-[#f0183d] px-6 py-2.5 text-[9px] font-black uppercase">START YOUR PROJECT <ChevronRight className="h-4 w-4" /></a></div><div className="grid grid-cols-3 gap-5 text-center">{[[Lightbulb, "YOUR IDEA", "You imagine it."], [Camera, "WE PRODUCE", "We bring it to life."], [Crown, "YOU OWN IT", "Rights stay with you."]].map(([Icon, title, body]) => <div key={title}><Icon className="mx-auto mb-3 h-9 w-9 text-[#f0183d]" /><h3 className="text-[10px] font-black uppercase">{title}</h3><p className="mt-1 text-[9px] text-white/54">{body}</p></div>)}</div><MediaImage src={FAN_IMAGE} alt="Fan production" className="hidden h-36 w-full rounded object-cover object-center md:block" /></div></section>

        <section className="border-b border-white/8 bg-[#080d10]"><div className="mx-auto grid max-w-[1360px] gap-4 px-5 py-5 md:grid-cols-5 lg:px-7">{trustCenter.map(([Icon, title, body]) => <div key={title} className="flex gap-3"><Icon className="h-8 w-8 shrink-0 text-[#f0183d]" /><div><h3 className="text-[10px] font-black uppercase">{title}</h3><p className="mt-1 text-[9px] leading-4 text-white/54">{body}</p></div></div>)}</div></section>

        <footer id="partners" className="bg-[#05080a]"><div className="mx-auto max-w-[1360px] px-5 py-6 lg:px-7"><div className="mb-5 flex flex-wrap items-center gap-7"><h2 className="fl-condensed text-[27px] uppercase tracking-[-0.02em] text-white/76">OUR TRUSTED <span className="text-[#f0183d]">PARTNERS</span></h2>{["xHamster", "FapHouse", "Clip4Sale", "LoyalFans", "ManyVids"].map((p) => <span key={p} className="text-lg font-black text-white/45">{p}</span>)}<a href="#" className="rounded border border-[#f0183d] px-4 py-1.5 text-[8px] font-black uppercase text-[#f0183d]">SEE ALL PARTNERS</a></div><div className="grid gap-8 border-t border-white/8 pt-5 md:grid-cols-[1fr_1fr_1fr_1fr_1.1fr]"><div><h3 className="text-sm font-black uppercase text-white/70">JOIN THE FLESHLAB FAMILY</h3><p className="mt-2 text-[10px] leading-4 text-white/45">Get updates, new releases and exclusive offers.</p><button className="mt-4 rounded bg-[#f0183d] px-7 py-2 text-[9px] font-black uppercase">SUBSCRIBE</button></div>{[["FOR PERFORMERS", ["How it works", "Requirements", "Payouts", "FAQ", "Support"]], ["FOR FANS", ["Videos", "Categories", "Fan Productions", "Membership", "FAQ"]], ["COMPANY", ["About us", "Blog", "Careers", "Press", "Contact"]], ["LEGAL", ["Terms of Service", "Privacy Policy", "DMCA", "Content Policy"]]].map(([title, items]) => <div key={title}><h3 className="mb-3 text-[9px] font-black uppercase text-white/72">{title}</h3>{items.map((item) => <a key={item} href="#" className="block text-[9px] leading-5 text-white/42 hover:text-white">{item}</a>)}</div>)}<div className="text-right"><Logo small /><p className="mt-4 text-[9px] text-white/42">© 2025 FLESHLAB Studios.<br />All rights reserved.</p></div></div></div></footer>
      </main>
    </div>
  );
}