export const landingCopy = {
  en: {
    nav: ["Who we are", "How it works", "Earn money", "Videos", "Trust"],
    heroKicker: "FLESHLAB creator ecosystem",
    heroTitle: "Your story starts before the camera turns on.",
    heroText: "A premium platform for real Asian amateur creators, studio-supported productions, verified fans, and long-term performer careers.",
    become: "Become performer",
    explore: "Explore videos",
    stats: ["Verified 18+ creators", "Monthly transparent payouts", "Admin-reviewed uploads"],
    choicesTitle: "Choose your journey",
    choicesSub: "Four clear entrances. One creator-first ecosystem.",
    journeyTitle: "From first upload to first payout.",
    journeySub: "Creators upload through the dashboard directly to Cloudflare R2. Every file is reviewed and approved by FLESHLAB before publication.",
    earnTitle: "Three ways to earn",
    earnSub: "Premium production models for different creator lives.",
    simulatorTitle: "Earnings simulator",
    worldsTitle: "Production worlds",
    worldsSub: "Not categories — cinematic worlds fans return to.",
    performersTitle: "Featured performers",
    fanTitle: "Fan productions",
    fanText: "Fans can apply to become part of a real FLESHLAB production with their favourite performer. The studio reviews every request, confirms consent, verifies every participant, and produces only approved projects.",
    trustTitle: "Trust center",
    partnerTitle: "Partners",
  },
  "zh-CN": {
    nav: ["我们是谁", "运作方式", "收入", "视频", "信任"],
    heroKicker: "FLESHLAB 创作者生态",
    heroTitle: "故事，从镜头开启前开始。",
    heroText: "为真实亚洲素人创作者打造的高级平台：工作室支持、已验证粉丝、合规制作与长期职业成长。",
    become: "成为表演者",
    explore: "探索视频",
    stats: ["18+ 已验证创作者", "每周付款流程", "团队审核上传"],
    choicesTitle: "选择你的路径",
    choicesSub: "四个入口，一个创作者优先的生态。",
    journeyTitle: "从首次上传到首次收入。",
    journeySub: "创作者通过仪表板直接上传到 Cloudflare R2。每个文件发布前都由 FLESHLAB 团队审核批准。",
    earnTitle: "三种收入方式",
    earnSub: "适合不同创作者生活方式的高级制作模式。",
    simulatorTitle: "收入模拟器",
    worldsTitle: "制作世界",
    worldsSub: "不是分类，而是粉丝会再次进入的电影化世界。",
    performersTitle: "精选表演者",
    fanTitle: "粉丝制作",
    fanText: "粉丝可以申请与喜欢的表演者一起参与真实 FLESHLAB 制作。工作室审核每个请求，确认同意，验证参与者，只制作获批项目。",
    trustTitle: "信任中心",
    partnerTitle: "合作伙伴",
  },
  th: {
    nav: ["เราเป็นใคร", "ทำงานอย่างไร", "รายได้", "วิดีโอ", "ความเชื่อมั่น"],
    heroKicker: "ระบบนิเวศครีเอเตอร์ FLESHLAB",
    heroTitle: "เรื่องราวของคุณเริ่มก่อนเปิดกล้อง",
    heroText: "แพลตฟอร์มพรีเมียมสำหรับครีเอเตอร์สมัครเล่นเอเชียจริง พร้อมโปรดักชันที่มีทีมสนับสนุน แฟนที่ยืนยันตัวตน และเส้นทางอาชีพระยะยาว",
    become: "สมัครเป็นนักแสดง",
    explore: "ดูวิดีโอ",
    stats: ["ครีเอเตอร์ 18+ ที่ยืนยันแล้ว", "ระบบจ่ายรายสัปดาห์", "อัปโหลดผ่านการรีวิว"],
    choicesTitle: "เลือกเส้นทางของคุณ",
    choicesSub: "สี่ทางเข้า ระบบเดียวที่ให้ครีเอเตอร์มาก่อน",
    journeyTitle: "จากอัปโหลดแรกสู่รายได้แรก",
    journeySub: "ครีเอเตอร์อัปโหลดผ่านแดชบอร์ดไปยัง Cloudflare R2 โดยตรง ทุกไฟล์ผ่านการตรวจและอนุมัติก่อนเผยแพร่",
    earnTitle: "สามวิธีสร้างรายได้",
    earnSub: "โมเดลโปรดักชันพรีเมียมสำหรับชีวิตครีเอเตอร์ที่ต่างกัน",
    simulatorTitle: "เครื่องจำลองรายได้",
    worldsTitle: "โลกของโปรดักชัน",
    worldsSub: "ไม่ใช่หมวดหมู่ แต่คือโลกภาพยนตร์ที่แฟนกลับมาอีก",
    performersTitle: "นักแสดงแนะนำ",
    fanTitle: "แฟนโปรดักชัน",
    fanText: "แฟนสามารถสมัครเข้าร่วมโปรดักชัน FLESHLAB จริงกับนักแสดงที่ชื่นชอบ ทีมงานตรวจทุกคำขอ ยืนยันความยินยอม ตรวจตัวตน และผลิตเฉพาะโปรเจกต์ที่อนุมัติแล้ว",
    trustTitle: "ศูนย์ความเชื่อมั่น",
    partnerTitle: "พาร์ทเนอร์",
  },
  tl: {
    nav: ["Sino kami", "Paano ito gumagana", "Kumita", "Videos", "Tiwala"],
    heroKicker: "FLESHLAB creator ecosystem",
    heroTitle: "Nagsisimula ang kuwento bago pa umandar ang camera.",
    heroText: "Premium platform para sa totoong Asian amateur creators, studio-supported productions, verified fans, at pangmatagalang performer careers.",
    become: "Maging performer",
    explore: "Explore videos",
    stats: ["Verified 18+ creators", "Monthly transparent payouts", "Admin-reviewed uploads"],
    choicesTitle: "Piliin ang journey mo",
    choicesSub: "Apat na malinaw na pasukan. Isang creator-first ecosystem.",
    journeyTitle: "Mula unang upload hanggang unang payout.",
    journeySub: "Direktang nag-a-upload ang creators sa dashboard papuntang Cloudflare R2. Lahat ng file ay nirereview at inaaprubahan muna ng FLESHLAB bago ilathala.",
    earnTitle: "Tatlong paraan kumita",
    earnSub: "Premium production models para sa iba’t ibang creator lifestyle.",
    simulatorTitle: "Earnings simulator",
    worldsTitle: "Production worlds",
    worldsSub: "Hindi generic categories — cinematic worlds na binabalikan ng fans.",
    performersTitle: "Featured performers",
    fanTitle: "Fan productions",
    fanText: "Puwedeng mag-apply ang fans para maging bahagi ng totoong FLESHLAB production kasama ang paboritong performer. Nirereview ng studio ang bawat request, kinukumpirma ang consent, vine-verify ang lahat, at approved projects lang ang ginagawa.",
    trustTitle: "Trust center",
    partnerTitle: "Partners",
  },
  vi: {
    nav: ["Chúng tôi là ai", "Cách hoạt động", "Kiếm tiền", "Video", "Tin cậy"],
    heroKicker: "Hệ sinh thái creator FLESHLAB",
    heroTitle: "Câu chuyện bắt đầu trước khi máy quay bật.",
    heroText: "Nền tảng cao cấp cho creator nghiệp dư châu Á thật, sản xuất có studio hỗ trợ, fan đã xác minh và sự nghiệp dài hạn.",
    become: "Trở thành performer",
    explore: "Khám phá video",
    stats: ["Creator 18+ đã xác minh", "Quy trình thanh toán hằng tuần", "Upload được đội ngũ duyệt"],
    choicesTitle: "Chọn hành trình của bạn",
    choicesSub: "Bốn lối vào rõ ràng. Một hệ sinh thái ưu tiên creator.",
    journeyTitle: "Từ upload đầu tiên đến khoản thu đầu tiên.",
    journeySub: "Creator upload trực tiếp qua dashboard lên Cloudflare R2. Mọi file đều được FLESHLAB xem xét và phê duyệt trước khi xuất bản.",
    earnTitle: "Ba cách kiếm tiền",
    earnSub: "Mô hình sản xuất cao cấp cho nhiều phong cách creator.",
    simulatorTitle: "Mô phỏng thu nhập",
    worldsTitle: "Thế giới sản xuất",
    worldsSub: "Không phải danh mục — mà là những thế giới điện ảnh fan muốn quay lại.",
    performersTitle: "Performer nổi bật",
    fanTitle: "Fan productions",
    fanText: "Fan có thể đăng ký tham gia một production FLESHLAB thật với performer yêu thích. Studio xem xét từng yêu cầu, xác nhận đồng thuận, xác minh người tham gia và chỉ sản xuất dự án được duyệt.",
    trustTitle: "Trust center",
    partnerTitle: "Đối tác",
  }
};

export function useLandingText(locale) {
  return landingCopy[locale] || landingCopy.en;
}