import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, CheckCircle2, Loader2, LogOut, RefreshCw, ShieldCheck } from 'lucide-react';
import { dashboards } from '@/api/fleshlabClient';
import { useAuth } from '@/lib/AuthContext';

function Loading() { return <div className="flex min-h-[40vh] items-center justify-center text-muted-foreground"><Loader2 className="mr-2 h-5 w-5 animate-spin" /> Loading your workspace…</div>; }
function Failure({ error, retry }) { return <div className="mx-auto max-w-xl rounded-2xl border border-red-500/30 bg-red-500/10 p-6 text-center"><AlertTriangle className="mx-auto h-7 w-7 text-red-400" /><h1 className="mt-3 text-lg font-bold">This workspace is unavailable</h1><p className="mt-2 text-sm text-muted-foreground">{error?.message || 'Please try again.'}</p><button onClick={retry} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground"><RefreshCw className="h-4 w-4" />Try again</button></div>; }
function Shell({ title, eyebrow, children }) { const { logout } = useAuth(); return <main className="min-h-screen bg-[#090909] px-4 py-7 text-white sm:px-8"><header className="mx-auto flex max-w-6xl items-center justify-between border-b border-white/10 pb-5"><Link to="/" className="font-black tracking-[.22em]">FLESHLAB</Link><button onClick={() => logout('/')} className="inline-flex items-center gap-2 text-sm text-white/60 hover:text-white"><LogOut className="h-4 w-4"/>Log out</button></header><section className="mx-auto max-w-6xl py-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-rose-400">{eyebrow}</p><h1 className="mt-2 text-3xl font-black tracking-tight">{title}</h1>{children}</section></main>; }
function MigrationNotice({ areas }) { return <div className="mt-6 rounded-xl border border-amber-400/25 bg-amber-400/10 p-4 text-sm text-amber-100"><div className="flex gap-2 font-semibold"><AlertTriangle className="h-5 w-5 shrink-0" />Some account areas are still being migrated</div><p className="mt-1 text-amber-100/80">{areas}. Empty values are intentional: this self-hosted deployment never displays made-up subscriptions, balances, purchases, media or earnings.</p></div>; }

export function CustomerDashboard() {
  const [data, setData] = useState(null); const [error, setError] = useState(null);
  const load = useCallback(() => { setError(null); dashboards.customer().then(setData).catch(setError); }, []);
  useEffect(load, [load]);
  if (error) return <Shell eyebrow="Account" title="Your dashboard"><Failure error={error} retry={load}/></Shell>;
  if (!data) return <Shell eyebrow="Account" title="Your dashboard"><Loading/></Shell>;
  const name = data.profile.display_name || data.user.email;
  return <Shell eyebrow="Account" title={`Welcome, ${name}`}><div className="mt-8 grid gap-4 md:grid-cols-3"><Card label="Subscriptions" value={data.subscriptions.length} description="No migrated subscription records"/><Card label="Payments" value={data.payments.length} description="No migrated payment records"/><Card label="Wallet" value="Not available" description="Ledger migration pending"/></div><MigrationNotice areas="Commerce, protected media and wallet history require their dedicated migration before they can be shown here."/><section className="mt-8 rounded-2xl border border-white/10 bg-white/[.03] p-6"><h2 className="font-bold">Notifications</h2>{data.notifications.length ? <ul className="mt-4 space-y-3">{data.notifications.map((item) => <li key={item.id} className="rounded-lg bg-white/[.04] p-3"><b>{item.title}</b><p className="mt-1 text-sm text-white/60">{item.body}</p></li>)}</ul> : <p className="mt-3 text-sm text-white/60">No account notifications yet.</p>}</section><ProfileEditor initial={data.profile} onSaved={(profile) => setData((current) => ({...current, profile}))}/></Shell>;
}

export function PerformerDashboardSelfHosted() {
  const [data, setData] = useState(null); const [error, setError] = useState(null);
  const load = useCallback(() => { setError(null); dashboards.performer().then(setData).catch(setError); }, []);
  useEffect(load, [load]);
  if (error) return <Shell eyebrow="Creator" title="Creator workspace"><Failure error={error} retry={load}/></Shell>;
  if (!data) return <Shell eyebrow="Creator" title="Creator workspace"><Loading/></Shell>;
  return <Shell eyebrow="Creator" title="Your Creator workspace">{data.performer ? <div className="mt-8 grid gap-4 md:grid-cols-3"><Card label="Performer profile" value={data.performer.full_name} description={`Status: ${data.performer.status}`}/><Card label="Application" value={data.performer.application_status} description={data.performer.country}/><Card label="Agreement" value={data.performer.contract_status || 'Not signed'} description={data.performer.signed_at ? 'Agreement recorded' : 'Contact FLESHLAB to complete it'}/></div> : <div className="mt-8 rounded-2xl border border-white/10 bg-white/[.03] p-6"><ShieldCheck className="h-7 w-7 text-rose-400"/><h2 className="mt-3 font-bold">Your performer account is not linked yet</h2><p className="mt-2 text-sm text-white/60">A FLESHLAB administrator must link your approved performer profile after the agreement is recorded.</p></div>}<MigrationNotice areas="Earnings, video catalogue, payout history and creator analytics are not migrated yet and remain unavailable rather than showing unreliable data."/></Shell>;
}

export function AdminDashboardSelfHosted() {
  const [data, setData] = useState(null); const [error, setError] = useState(null);
  const load = useCallback(() => { setError(null); dashboards.admin().then(setData).catch(setError); }, []);
  useEffect(load, [load]);
  if (error) return <Failure error={error} retry={load}/>;
  if (!data) return <Loading/>;
  return <div className="space-y-7"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-rose-500">Self-hosted control room</p><h1 className="mt-2 text-3xl font-black">FLESHLAB HQ</h1><p className="mt-2 text-sm text-muted-foreground">Only migrated records are shown. The dashboard does not fall back to Base44.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="Applications" value={data.metrics.applications_total}/><Card label="Needs review" value={data.metrics.applications_pending}/><Card label="Active performers" value={data.metrics.active_performers}/><Card label="Active accounts" value={data.metrics.active_accounts}/></div><div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Recent applications</h2><Link className="text-sm font-semibold text-primary hover:underline" to="/admin/applications">Open review queue</Link></div>{data.recent_applications.length ? <ul className="mt-4 divide-y divide-border">{data.recent_applications.map((app) => <li key={app.id} className="flex justify-between gap-3 py-3 text-sm"><span><b>{app.full_name}</b><span className="ml-2 text-muted-foreground">{app.country}</span></span><span className="rounded-full bg-muted px-2 py-0.5 text-xs">{app.status}</span></li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">No self-hosted applications yet.</p>}</div><MigrationNotice areas="Catalogue, revenue, payment, wallet and media administration have separate data migrations and are not represented as live production data in this dashboard."/></div>;
}

export function AdminApplicationsSelfHosted() {
  const [data, setData] = useState(null); const [error, setError] = useState(null); const [detail, setDetail] = useState(null); const [busy, setBusy] = useState(false);
  const load = useCallback(() => { setError(null); dashboards.applications().then(setData).catch(setError); }, []);
  useEffect(load, [load]);
  const open = async (id) => { setError(null); try { setDetail(await dashboards.application(id)); } catch (err) { setError(err); } };
  const setReview = async (status) => { if (!detail) return; setBusy(true); try { await dashboards.review(detail.application.id, {status}); setDetail(await dashboards.application(detail.application.id)); load(); } catch (err) { setError(err); } finally { setBusy(false); } };
  const approve = async () => { if (!detail) return; setBusy(true); try { await dashboards.approve(detail.application.id); setDetail(await dashboards.application(detail.application.id)); load(); } catch (err) { setError(err); } finally { setBusy(false); } };
  if (error) return <Failure error={error} retry={load}/>;
  if (!data) return <Loading/>;
  return <div className="grid gap-6 xl:grid-cols-[1fr_1.1fr]"><section><p className="text-xs font-bold uppercase tracking-[.2em] text-rose-500">Recruiting</p><h1 className="mt-2 text-3xl font-black">Application review</h1><div className="mt-6 divide-y divide-border rounded-2xl border border-border bg-card">{data.applications.map((app) => <button onClick={() => open(app.id)} key={app.id} className="flex w-full items-center justify-between gap-3 p-4 text-left hover:bg-muted/50"><span><b>{app.full_name}</b><span className="ml-2 text-sm text-muted-foreground">{app.country}</span></span><span className="rounded-full bg-muted px-2 py-1 text-xs">{app.status}</span></button>)}{!data.applications.length && <p className="p-5 text-sm text-muted-foreground">No applications submitted in this self-hosted environment.</p>}</div></section><section className="rounded-2xl border border-border bg-card p-5">{detail ? <><h2 className="text-xl font-bold">{detail.application.full_name}</h2><p className="mt-1 text-sm text-muted-foreground">{detail.application.country} · {detail.application.status}</p><div className="mt-5 grid gap-3 text-sm"><Status label="Age confirmation" ok={detail.application.age_confirmed}/><Status label="Consent" ok={detail.application.consent_confirmed}/><Status label="Confirmed documents" ok={detail.uploads.some((upload) => upload.status === 'confirmed')}/><Status label="Application complete" ok={detail.complete}/></div><div className="mt-6 flex flex-wrap gap-2"><button disabled={busy} onClick={() => setReview('under_review')} className="rounded-lg border border-border px-3 py-2 text-sm font-semibold">Mark under review</button><button disabled={busy} onClick={() => setReview('rejected')} className="rounded-lg border border-red-500/40 px-3 py-2 text-sm font-semibold text-red-500">Reject</button><button disabled={busy || !detail.complete} onClick={approve} className="rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground">Approve</button></div>{detail.profile && <p className="mt-5 text-sm text-muted-foreground">Performer profile: {detail.profile.status}. Contract recording and account assignment stay protected server-side steps.</p>}</> : <p className="text-sm text-muted-foreground">Choose an application to review its confirmed state.</p>}</section></div>;
}

function ProfileEditor({ initial, onSaved }) { const [name, setName] = useState(initial.display_name || ''); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const save = async () => { setSaving(true); setMessage(''); try { const result = await dashboards.updateProfile({display_name: name}); onSaved(result.profile); setMessage('Saved.'); } catch (error) { setMessage(error.message); } finally { setSaving(false); } }; return <section className="mt-8 rounded-2xl border border-white/10 bg-white/[.03] p-6"><h2 className="font-bold">Profile</h2><label className="mt-4 block text-sm text-white/70">Display name<input value={name} maxLength={120} onChange={(event) => setName(event.target.value)} className="mt-2 w-full rounded-lg border border-white/15 bg-black/30 px-3 py-2 text-white"/></label><button disabled={saving} onClick={save} className="mt-3 rounded-lg bg-white px-4 py-2 text-sm font-bold text-black disabled:opacity-50">{saving ? 'Saving…' : 'Save profile'}</button>{message && <p className="mt-2 text-sm text-white/60">{message}</p>}</section>; }
function Card({ label, value, description }) { return <article className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-white/45">{label}</p><p className="mt-3 text-2xl font-black">{value ?? '—'}</p>{description && <p className="mt-2 text-sm text-white/55">{description}</p>}</article>; }
function Status({ label, ok }) { return <div className="flex items-center gap-2"><CheckCircle2 className={`h-4 w-4 ${ok ? 'text-emerald-500' : 'text-white/25'}`}/><span>{label}</span></div>; }
