import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';

const APPROVED = new Set(['approved','contract_pending','contract_sent','contract_signed','performer_created','user_linked','active']);
const REVIEW = new Set(['pending','media_pending','reviewing','more_info_requested']);
function daysSince(v) { if (!v) return 0; return Math.max(0, Math.floor((Date.now() - new Date(v).getTime()) / 86400000)); }
function score(app) { let s = 35; if (app.email) s += 8; if (app.phone) s += 8; if (app.nationality || app.source_country) s += 6; if (app.package_interest && app.package_interest !== 'not_sure') s += 8; if ((app.profile_photo_r2_keys || []).length >= 5) s += 8; if (app.intro_video_r2_key && app.hardcore_video_r2_key) s += 8; if ((app.id_document_front_r2_key || app.id_document_r2_key) && app.selfie_with_id_r2_key) s += 12; if (APPROVED.has(app.status)) s += 14; if (app.status === 'rejected') s -= 35; if (daysSince(app.updated_date || app.created_date) > 7 && REVIEW.has(app.status)) s -= 10; return Math.max(0, Math.min(100, s)); }
function timeline(app) { const events = [['Submitted', app.submitted_at || app.created_date, app.source_page || 'Recruitment flow', 'info'], ['Review started', app.review_started_at, 'Team review opened', 'info'], ['More info requested', app.more_info_requested_at, app.more_info_request_message || 'Waiting for applicant response', 'warning'], ['Approved', app.approved_at, 'Ready for contract or next step', 'success'], ['Rejected', app.rejected_at, app.rejection_reason || 'Application did not move forward', 'danger'], ['Contract sent', app.contract_sent_at, 'Awaiting signature', 'warning'], ['Contract signed', app.contract_signed_at, 'Ready for production planning', 'success'], ['Performer created', app.performer_created_at, app.performer_id || 'Performer profile created', 'success'], ['Activated', app.activated_at, 'Creator is active', 'success']]; return events.filter(e => e[1]).map(([label,date,detail,tone]) => ({label,date,detail,tone})).sort((a,b) => new Date(a.date) - new Date(b.date)); }
function profile(app) { const staleDays = daysSince(app.updated_date || app.created_date); const val = score(app); const hasUploads = (app.profile_photo_r2_keys || []).length >= 5 && app.intro_video_r2_key && app.hardcore_video_r2_key; const hasCompliance = (app.id_document_front_r2_key || app.id_document_r2_key) && app.selfie_with_id_r2_key; const cold = staleDays >= 5 && REVIEW.has(app.status); let bucket = 'Review queue'; let nextAction = 'Open profile and decide whether to continue review.'; let tone = 'Direct, professional, low-pressure'; let followUp = 'Today'; const concerns = []; const missing = []; if ((app.profile_photo_r2_keys || []).length < 5) missing.push('review photos'); if (!app.intro_video_r2_key || !app.hardcore_video_r2_key) missing.push('review videos'); if (!hasCompliance) missing.push('ID / selfie verification'); if (!app.phone) missing.push('direct contact channel'); if (cold) concerns.push('Applicant is becoming cold'); if (APPROVED.has(app.status)) { bucket = 'Ready for production'; nextAction = 'Move to production planning or contract completion.'; tone = 'Confident and practical'; } else if (hasUploads && !hasCompliance) { bucket = 'Ready for verification'; nextAction = 'Ask for ID/selfie verification and explain privacy handling.'; tone = 'Reassuring and specific'; } else if (cold) { bucket = 'Becoming cold'; nextAction = 'Send a short reassurance follow-up with one clear next step.'; tone = 'Warm, calm, no pressure'; followUp = 'Within 24 hours'; } else if (val >= 70) { bucket = 'High potential'; nextAction = 'Prioritize review and invite them to the next milestone.'; tone = 'Encouraging and concrete'; } else if (app.status === 'rejected') { bucket = 'Reject / archive'; nextAction = 'Confirm rejection reason is documented and close the loop.'; tone = 'Clear and respectful'; followUp = 'No follow-up unless requested'; } return { id: app.id, name: app.applicant_name || 'Unnamed applicant', country: app.nationality || app.source_country || 'Unknown', path: app.package_interest || 'not specified', source: app.utm_source || app.source_page || 'direct', status: app.status || 'pending', score: val, ageDays: daysSince(app.created_date), staleDays, bucket, nextAction, tone, followUp, concerns, missing, approvalLikelihood: Math.min(95, Math.max(10, val + (hasCompliance ? 8 : -8))), productionLikelihood: Math.min(90, Math.max(5, val + (APPROVED.has(app.status) ? 20 : hasUploads ? 5 : -15))), timeline: timeline(app) }; }
function group(items, key) { return items.reduce((a, x) => { const k = x[key] || 'Unknown'; a[k] = (a[k] || 0) + 1; return a; }, {}); }

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user || user.role !== 'admin') return Response.json({ error: 'Admin access required' }, { status: 403 });
    const { days = 30, skip = 0, limit = 50 } = await req.json();
    const cutoff = new Date(Date.now() - Number(days) * 86400000).toISOString();
    const appsRaw = await base44.asServiceRole.entities.GuestProductionApplication.filter({ request_type: 'performer_application' }, '-created_date', 500);
    const performers = await base44.asServiceRole.entities.Performer.list('-created_date', 500);
    const apps = appsRaw.filter(a => a.created_date >= cutoff);
    const profiles = apps.map(profile).sort((a,b) => b.score - a.score || b.staleDays - a.staleDays);
    const attention = profiles.filter(p => ['Ready for production','Ready for verification','Becoming cold','High potential'].includes(p.bucket)).slice(0, 20);
    const page = profiles.slice(Number(skip), Number(skip) + Math.min(Number(limit), 100));
    const today = new Date().toISOString().slice(0,10);
    const metrics = { applicationsToday: apps.filter(a => String(a.created_date || '').startsWith(today)).length, qualified: profiles.filter(p => p.score >= 70).length, approvalRate: apps.length ? Math.round((apps.filter(a => APPROVED.has(a.status)).length / apps.length) * 100) : 0, rejectionRate: apps.length ? Math.round((apps.filter(a => a.status === 'rejected').length / apps.length) * 100) : 0, waitingTooLong: profiles.filter(p => p.staleDays >= 5 && REVIEW.has(p.status)).length, readyForVerification: profiles.filter(p => p.bucket === 'Ready for verification').length, readyForProduction: profiles.filter(p => p.bucket === 'Ready for production').length, activeCreators: performers.filter(p => p.status === 'active').length, avgReviewAge: profiles.length ? Math.round(profiles.reduce((sum,p) => sum + p.ageDays, 0) / profiles.length) : 0, eventSignals: 0 };
    const bottlenecks = []; if (metrics.waitingTooLong) bottlenecks.push({ title:'Review backlog', detail:`${metrics.waitingTooLong} applicants have waited 5+ days.`, action:'Clear oldest high-score profiles first.' }); if (metrics.readyForVerification) bottlenecks.push({ title:'Verification backlog', detail:`${metrics.readyForVerification} applicants need verification.`, action:'Send privacy-first verification follow-up.' }); if (metrics.readyForProduction) bottlenecks.push({ title:'Production scheduling', detail:`${metrics.readyForProduction} applicants are ready for next steps.`, action:'Move approved applicants into planning.' }); if (!bottlenecks.length) bottlenecks.push({ title:'Pipeline stable', detail:'No critical recruitment bottleneck detected.', action:'Review high-potential profiles.' });
    return Response.json({ success: true, workspace: { profiles: page, attention, metrics, breakdowns: { byCountry: group(profiles, 'country'), byPath: group(profiles, 'path'), bySource: group(profiles, 'source') }, bottlenecks, pagination: { skip, limit, total: profiles.length, has_more: skip + limit < profiles.length } }, dateRange: `${new Date(cutoff).toLocaleDateString()} → ${new Date().toLocaleDateString()}` });
  } catch (error) { return Response.json({ error: error.message }, { status: 500 }); }
});