import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    
    const user = await base44.auth.me();
    if (!user || user.role !== 'admin') {
      return Response.json({ error: 'Forbidden: Admin access required' }, { status: 403 });
    }

    // Fetch current V2 state
    const [performers, videos, brands, contracts, fanclubs, applications, complianceRecords] = await Promise.all([
      base44.entities.Performer.list(),
      base44.entities.Video.list(),
      base44.entities.Brand.list(),
      base44.entities.Contract.list(),
      base44.entities.Fanclub.list(),
      base44.entities.GuestProductionApplication.list(),
      base44.entities.ComplianceRecord ? await base44.entities.ComplianceRecord.list() : [],
    ]);

    const audit = {
      audit_timestamp: new Date().toISOString(),
      audit_scope: 'V1 → V2 Backoffice Migration Planning',
      v2_current_state: {
        performers: { count: performers.length, with_v1_id: performers.filter(p => p.v1_id).length },
        videos: { count: videos.length, with_v1_id: videos.filter(v => v.v1_id).length },
        brands: { count: brands.length, with_v1_id: brands.filter(b => b.v1_id).length },
        contracts: { count: contracts.length },
        fanclubs: { count: fanclubs.length },
        guest_applications: { count: applications.length },
        compliance_records: { count: Array.isArray(complianceRecords) ? complianceRecords.length : 0 },
      },
      v1_backoffice_entities: {
        note: 'V1 API does not expose backoffice entities via REST. Analysis based on V2 entity requirements.',
        entities: {
          PerformerApplication: {
            estimated_count: 'Unknown (likely 19+ based on performer count)',
            fields: ['applicant_name', 'email', 'phone', 'nationality', 'message', 'package_interest', 'id_document_url', 'status', 'admin_notes', 'submitted_at'],
            relationship_to_performer: '1:1 - Application becomes Performer upon approval',
            relationship_to_video: 'None direct',
            relationship_to_application: 'Source entity',
            file_fields: ['id_document_url'],
            sensitive_fields: ['email', 'phone', 'id_document_url', 'nationality', 'date_of_birth'],
            required_for_v2_launch: true,
            post_launch_only: false,
            do_not_migrate_fields: ['internal_admin_notes', 'legacy_id'],
            v2_mapping: 'GuestProductionApplication',
            migration_priority: 'CRITICAL',
          },
          PerformerContract: {
            estimated_count: 'Unknown (likely 17+ based on active performers)',
            fields: ['performer_id', 'contract_type', 'title', 'status', 'signed_at', 'expires_at', 'document_url', 'notes'],
            relationship_to_performer: '1:1 or 1:many - Performer has contract(s)',
            relationship_to_video: 'Indirect via performer eligibility',
            relationship_to_application: 'Follows approved application',
            file_fields: ['document_url'],
            sensitive_fields: ['payment_terms', 'revenue_split', 'bank_details', 'tax_id'],
            required_for_v2_launch: true,
            post_launch_only: false,
            do_not_migrate_fields: ['internal_approval_chain', 'legacy_contract_id'],
            v2_mapping: 'Contract (contract_type="performer")',
            migration_priority: 'CRITICAL',
          },
          ContractSignature: {
            estimated_count: 'Unknown (matches contract count)',
            fields: ['contract_id', 'performer_id', 'signature_image_url', 'signed_document_url', 'ip_address', 'user_agent', 'signed_at'],
            relationship_to_performer: 'Performer signs contract',
            relationship_to_video: 'None',
            relationship_to_application: 'None',
            file_fields: ['signature_image_url', 'signed_document_url'],
            sensitive_fields: ['signature_image', 'ip_address', 'user_agent'],
            required_for_v2_launch: false,
            post_launch_only: false,
            do_not_migrate_fields: ['audit_trail_metadata'],
            v2_mapping: 'Merge into Contract entity (signed_at, document_url fields exist)',
            migration_priority: 'MEDIUM',
          },
          PartnerComplianceDocument: {
            estimated_count: 'Unknown (likely 17+ for active performers)',
            fields: ['performer_id', 'document_type', 'document_url', 'issued_at', 'expires_at', 'status', 'issuing_authority'],
            relationship_to_performer: '1:many - Performer has multiple compliance docs',
            relationship_to_video: 'Required for video publishing eligibility',
            relationship_to_application: 'Part of application approval process',
            file_fields: ['document_url', 'id_scan_url', 'test_results_url'],
            sensitive_fields: ['medical_test_results', 'std_test_dates', 'government_id_number'],
            required_for_v2_launch: true,
            post_launch_only: false,
            do_not_migrate_fields: ['internal_reviewer_notes'],
            v2_mapping: 'ComplianceRecord (entity does not exist yet - needs creation)',
            migration_priority: 'CRITICAL',
          },
          PartnerProductionCompliance: {
            estimated_count: 'Unknown',
            fields: ['performer_id', 'production_id', 'compliance_status', 'restrictions', 'medical_clearance'],
            relationship_to_performer: '1:many - Per production',
            relationship_to_video: 'Required for specific video productions',
            relationship_to_application: 'Post-application',
            file_fields: ['compliance_certificate_url'],
            sensitive_fields: ['medical_clearance', 'availability_restrictions'],
            required_for_v2_launch: false,
            post_launch_only: true,
            do_not_migrate_fields: [],
            v2_mapping: 'Post-launch: extend ComplianceRecord or create ProductionCompliance entity',
            migration_priority: 'LOW',
          },
          ProductionCompatibilityProfile: {
            estimated_count: 'Unknown (likely <17)',
            fields: ['performer_id', 'preferences', 'hard_limits', 'soft_limits', 'health_conditions', 'scene_notes'],
            relationship_to_performer: '1:1 - Extended performer profile',
            relationship_to_video: 'Informs production planning',
            relationship_to_application: 'Extended application data',
            file_fields: [],
            sensitive_fields: ['sexual_preferences', 'hard_limits', 'soft_limits', 'health_conditions'],
            required_for_v2_launch: false,
            post_launch_only: true,
            do_not_migrate_fields: ['internal_scene_notes'],
            v2_mapping: 'Post-launch: add to Performer.bio or create PerformerProfile entity',
            migration_priority: 'LOW',
          },
          PerformerEarnings: {
            estimated_count: 'Unknown (depends on revenue model)',
            fields: ['performer_id', 'video_id', 'amount_usd', 'earning_type', 'period', 'payment_method'],
            relationship_to_performer: '1:many - Earnings per video/period',
            relationship_to_video: 'Revenue attribution per video',
            relationship_to_application: 'None',
            file_fields: [],
            sensitive_fields: ['amount_usd', 'payment_method', 'bank_account', 'tax_withholding'],
            required_for_v2_launch: false,
            post_launch_only: true,
            do_not_migrate_fields: ['internal_accounting_codes'],
            v2_mapping: 'Payment entity (extend with performer_id relationship)',
            migration_priority: 'LOW',
          },
          PerformerPayoutBatch: {
            estimated_count: 'Unknown',
            fields: ['batch_id', 'performer_ids', 'total_amount', 'payout_date', 'status', 'receipt_url'],
            relationship_to_performer: '1:many - Batch includes multiple performers',
            relationship_to_video: 'Indirect via earnings',
            relationship_to_application: 'None',
            file_fields: ['payout_receipt_url'],
            sensitive_fields: ['total_amount', 'bank_transfer_details', 'tax_forms'],
            required_for_v2_launch: false,
            post_launch_only: true,
            do_not_migrate_fields: ['accounting_batch_id'],
            v2_mapping: 'Payment entity (batch payout extension)',
            migration_priority: 'LOW',
          },
          PerformerRevenue: {
            estimated_count: 'Unknown',
            fields: ['performer_id', 'video_id', 'revenue_amount', 'revenue_source', 'split_percentage', 'period'],
            relationship_to_performer: '1:many - Revenue attribution',
            relationship_to_video: 'Per-video revenue',
            relationship_to_application: 'None',
            file_fields: [],
            sensitive_fields: ['revenue_amount', 'split_percentage'],
            required_for_v2_launch: false,
            post_launch_only: true,
            do_not_migrate_fields: ['internal_ledger_codes'],
            v2_mapping: 'Aggregate from Payment entity - no separate migration',
            migration_priority: 'LOW',
          },
          PerformerGuestProductionMedia: {
            estimated_count: 'Unknown',
            fields: ['performer_id', 'media_type', 'media_url', 'thumbnail_url', 'caption'],
            relationship_to_performer: '1:many - Portfolio media',
            relationship_to_video: 'May be used in production',
            relationship_to_application: 'Application attachments',
            file_fields: ['media_url', 'thumbnail_url'],
            sensitive_fields: [],
            required_for_v2_launch: false,
            post_launch_only: true,
            do_not_migrate_fields: [],
            v2_mapping: 'VideoAsset entity or create Portfolio entity',
            migration_priority: 'LOW',
          },
          GuestProductionApplicantMedia: {
            estimated_count: 'Unknown',
            fields: ['application_id', 'media_type', 'media_url', 'document_type'],
            relationship_to_performer: 'Via application',
            relationship_to_video: 'None',
            relationship_to_application: '1:many - Application attachments',
            file_fields: ['media_url', 'document_url'],
            sensitive_fields: ['id_document_url'],
            required_for_v2_launch: true,
            post_launch_only: false,
            do_not_migrate_fields: [],
            v2_mapping: 'Merge into GuestProductionApplication (id_document_url field)',
            migration_priority: 'MEDIUM',
          },
          GuestProductionApplication: {
            estimated_count: 'Unknown (likely matches PerformerApplication)',
            fields: ['applicant_name', 'email', 'phone', 'nationality', 'message', 'package_interest', 'id_document_url', 'status'],
            relationship_to_performer: '1:1 or 1:many',
            relationship_to_video: 'May result in video production',
            relationship_to_application: 'Primary application entity',
            file_fields: ['id_document_url'],
            sensitive_fields: ['phone', 'email', 'id_document_url'],
            required_for_v2_launch: true,
            post_launch_only: false,
            do_not_migrate_fields: ['internal_review_status'],
            v2_mapping: 'GuestProductionApplication (already exists)',
            migration_priority: 'CRITICAL',
          },
          GuestProductionPackage: {
            estimated_count: 'Unknown (likely 3-10 packages)',
            fields: ['package_name', 'description', 'price', 'revenue_split', 'deliverables'],
            relationship_to_performer: 'Selected by performer',
            relationship_to_video: 'Defines production scope',
            relationship_to_application: 'Application includes package',
            file_fields: [],
            sensitive_fields: ['pricing', 'revenue_split'],
            required_for_v2_launch: false,
            post_launch_only: true,
            do_not_migrate_fields: ['internal_cost_basis'],
            v2_mapping: 'Static configuration or extend GuestProductionApplication',
            migration_priority: 'LOW',
          },
          ContractTemplate: {
            estimated_count: 'Unknown (likely 3-5 templates)',
            fields: ['template_name', 'template_type', 'document_url', 'version', 'legal_terms'],
            relationship_to_performer: 'Template for performer contracts',
            relationship_to_video: 'None',
            relationship_to_application: 'None',
            file_fields: ['template_document_url'],
            sensitive_fields: ['legal_terms'],
            required_for_v2_launch: false,
            post_launch_only: true,
            do_not_migrate_fields: [],
            v2_mapping: 'Static document storage (no entity needed)',
            migration_priority: 'LOW',
          },
          GuestProductionReleaseTemplate: {
            estimated_count: 'Unknown (likely 1-3 templates)',
            fields: ['template_name', 'release_type', 'document_url', 'jurisdiction'],
            relationship_to_performer: 'Release form for performer',
            relationship_to_video: 'Required per video production',
            relationship_to_application: 'Post-application',
            file_fields: ['release_form_url'],
            sensitive_fields: ['legal_terms'],
            required_for_v2_launch: false,
            post_launch_only: true,
            do_not_migrate_fields: [],
            v2_mapping: 'Static document storage (link from Contract)',
            migration_priority: 'LOW',
          },
        },
      },
      migration_categorization: {
        required_for_v2_launch: {
          entities: [
            'PerformerApplication → GuestProductionApplication',
            'PerformerContract → Contract',
            'PartnerComplianceDocument → ComplianceRecord (NEW ENTITY REQUIRED)',
            'GuestProductionApplication → GuestProductionApplication',
            'GuestProductionApplicantMedia → Merge into applications',
          ],
          rationale: 'These entities are essential for performer onboarding, legal compliance, and studio operations.',
          estimated_records: '50-100 total records',
        },
        post_launch_only: {
          entities: [
            'PartnerProductionCompliance',
            'ProductionCompatibilityProfile',
            'PerformerEarnings',
            'PerformerPayoutBatch',
            'PerformerRevenue',
            'PerformerGuestProductionMedia',
            'GuestProductionPackage',
            'ContractTemplate',
            'GuestProductionReleaseTemplate',
          ],
          rationale: 'These support payment processing, advanced production management, and revenue tracking - not needed for initial launch.',
          estimated_records: '100-500 total records',
        },
        do_not_migrate: {
          fields: [
            'Password hashes (re-authenticate users)',
            'Internal admin notes (re-create in V2)',
            'Legacy IDs (use v1_id field for mapping)',
            'Internal accounting codes (use V2 system)',
            'Audit trail metadata (start fresh in V2)',
            'IP addresses / user agents (privacy)',
          ],
          rationale: 'These fields are either security-sensitive, internal-only, or better handled by V2 systems.',
        },
      },
      sensitive_data_handling: {
        id_documents: {
          storage: 'Private R2 bucket (not public CDN)',
          access: 'Admin-only via signed URLs',
          encryption: 'Encrypt at rest',
          retention: '7 years minimum (legal requirement)',
        },
        medical_records: {
          storage: 'Separate private bucket with enhanced access control',
          access: 'Admin + compliance officer only',
          encryption: 'Encrypt at rest and in transit',
          retention: 'Per local regulations',
        },
        bank_details: {
          recommendation: 'DO NOT MIGRATE - re-collect in V2',
          rationale: 'PCI compliance, data freshness',
        },
        tax_information: {
          storage: 'Encrypted fields, admin-only access',
          access_logging: 'Required',
        },
        signatures: {
          storage: 'Image URLs with access control',
          legal_validity: 'Verify e-signature compliance',
        },
      },
      relationship_mapping: {
        performer_to_application: '1:1 or 1:many (Performer may have multiple applications)',
        performer_to_contract: '1:1 or 1:many (Contracts may be renewed)',
        performer_to_compliance: '1:many (Multiple compliance documents over time)',
        contract_to_signature: '1:1 (Signature merged into Contract)',
        application_to_media: '1:many (Multiple attachments)',
        performer_to_video: 'many:many (via VideoPerformer junction)',
        video_to_assets: '1:many (Multiple assets per video)',
      },
      export_function_plan: {
        prerequisite: 'V1 data export required (CSV/JSON from V1 database)',
        note: 'V1 API does not expose backoffice endpoints. Manual export from V1 admin required.',
        stages: [
          {
            stage: 1,
            entity: 'GuestProductionApplication',
            source: 'V1 PerformerApplication + GuestProductionApplication export',
            transform: 'Merge application data, map status values, attach media URLs',
            v2_function: 'importGuestApplicationsFromV1',
            estimated_time: '5 minutes',
          },
          {
            stage: 2,
            entity: 'Contract',
            source: 'V1 PerformerContract + ContractSignature export',
            transform: 'Map contract_type="performer", merge signature data (signed_at, document_url)',
            v2_function: 'importContractsFromV1',
            estimated_time: '5 minutes',
          },
          {
            stage: 3,
            entity: 'ComplianceRecord',
            source: 'V1 PartnerComplianceDocument export',
            transform: 'Create new V2 entity (requires entity creation first)',
            v2_function: 'importComplianceRecordsFromV1',
            prerequisite: 'Create ComplianceRecord entity in V2',
            estimated_time: '10 minutes',
          },
        ],
      },
      v2_import_plan: {
        prerequisites: [
          'Performers already migrated with v1_id mapping (✅ DONE - 17 performers)',
          'ComplianceRecord entity created in V2 schema',
          'Private R2 bucket configured for document storage',
          'Admin users configured in V2',
          'V1 data exported to CSV/JSON format',
        ],
        import_order: [
          '1. GuestProductionApplication (no dependencies)',
          '2. Contract (depends on: Performer v1_id mapping)',
          '3. ComplianceRecord (depends on: Performer, optionally Video)',
        ],
        validation_steps: [
          'Verify all performer_id references resolve to existing V2 performers',
          'Verify all file URLs are accessible (R2 migration may be needed)',
          'Verify contract signed_at dates are valid ISO 8601',
          'Verify compliance documents have not expired',
          'Verify application status values match V2 enum',
        ],
        rollback_plan: 'Delete imported records using v1_id filter if import fails',
      },
      entity_creation_required: {
        ComplianceRecord: {
          status: 'NOT EXISTS - MUST CREATE',
          suggested_schema: {
            performer_id: 'string (required)',
            video_id: 'string (optional)',
            document_type: 'enum (id, medical_test, std_test, background_check, other)',
            document_url: 'string (required)',
            issued_at: 'date-time',
            expires_at: 'date-time (optional)',
            status: 'enum (valid, expiring_soon, expired, revoked)',
            issuing_authority: 'string (optional)',
            notes: 'string (optional)',
          },
        },
      },
      go_no_go_recommendation: {
        recommendation: 'CONDITIONAL GO',
        conditions: [
          '✅ Core content migrated (Performers: 17, Videos: 88, Brands: 4)',
          '⚠️  ComplianceRecord entity must be created before backoffice migration',
          '⚠️  V1 backoffice data must be exported manually (API not available)',
          '⚠️  Private R2 bucket must be configured for sensitive documents',
          '⚠️  Admin users must be configured in V2',
        ],
        risk_level: 'MEDIUM',
        rationale: 'V2 is operational for public content (videos, performers, brands). Backoffice migration requires manual V1 data export and ComplianceRecord entity creation. No technical blockers, but requires admin workflow completion.',
        estimated_migration_time: '30-60 minutes (including data export, entity creation, and import)',
        post_launch_items: [
          'Payment/revenue tracking (PerformerEarnings, PerformerPayoutBatch)',
          'Production compliance (PartnerProductionCompliance)',
          'Performer preferences (ProductionCompatibilityProfile)',
          'Contract templates (static storage)',
        ],
      },
    };

    return Response.json(audit);
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});